<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 sponsors-new">
		
		<h2>Verificar Autenticidade</h2>

		<?php require_once "_form.phtml"; ?>

		<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-search"></span> <?= $this->titleBtnSubmit?></button>

		<br/>
		<br/>

		<?php if($this->certificate->getIdCertificate()) : ?>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
					<ul class="list-group">
						<li class="list-group-item">Código do certificado: <b><?= $this->certificate->getCode() ?></b></li>
						<li class="list-group-item">Participante: <b><?= strtoupper($this->participant->getName()) ?></b></li>
						<li class="list-group-item">Evento: <b><?= $this->event->getName()?></b></li>
						<li class="list-group-item">Data: <?= strtotime($this->event->getStartDate("d/m/Y")) != strtotime($this->event->getEndDate("d/m/Y")) ? "Entre " . $this->event->getStartDate("d/m/Y") . " e " . $this->event->getEndDate("d/m/Y") : "" . $this->event->getStartDate("d/m/Y") ?></li>
						<li class="list-group-item">Carga horária total: <b><?= ceil((strtotime($this->event->getEndDate("d/m/Y H:s")) - strtotime($this->event->getStartDate("d/m/Y H:s"))) / 3600 )?> horas</b></li>
					</ul>
				</div>
			</div>
		<?php endif; ?>

		<br/>
		<br/>

		</form>
	</div>
</div>