<div id="footer" class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="row">
			<div id="footer-links" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
				<ul>
					<li><a href="<?php echo $this->getUri(); ?>">Home</a></li>
					<li><a href="<?php echo $this->getUri('eventos/proximos'); ?>">Próximos Eventos</a></li>
					<li><a href="<?php echo $this->getUri('eventos/anteriores'); ?>">Eventos Anteriores</a></li>
					<li><a href="<?php echo $this->getUri('noticias/lista'); ?>">Notícias</a></li>
					<li><a href="<?php echo $this->getUri('midia/galeria'); ?>">Fotos e Vídeos</a></li>
					<li><a href="<?php echo $this->getUri('contato'); ?>">Contato</a></li>
					<li><a href="<?php echo $this->getUri('conta/login'); ?>">Painel</a></li>
				</ul>
			</div>
			<div id="footer-links2" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
				<a href="http://www.utfpr.edu.br/guarapuava" target="blank"><div class="utfpr-link col-xs-2"><img src="<?php echo RESOURCES_FOLDER.'/img/utfpr.png'; ?>"/></div></a>
				<a href="http://www.facebook.com/UtfprGP" target="blank"><div class="facebook-link col-xs-2"></div></a>
				<a href=""><div class="youtube-link col-xs-2"></div></a>
			</div>
		</div>
		<div class="row">
			<div id="footer-info" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
				UTFPR 2014 - Site em Desenvolvimento por Gustavo Pchek e Rodrigo Miss
			</div>
		</div>
	</div>
</div>