<footer id="footer" class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="row">
			<div id="footer-links" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
				<div class="col-xs-12 col-sm-12 col-md-6">
					<ul>
						<li><a href="<?= $this->getUri(); ?>">Home</a></li>
						<li><a href="<?= $this->getUri('eventos/proximos'); ?>">Próximos Eventos</a></li>
						<li><a href="<?= $this->getUri('eventos/anteriores'); ?>">Eventos Anteriores</a></li>
						<li><a href="<?= $this->getUri('noticias/lista'); ?>">Notícias</a></li>
						<li><a href="<?= $this->getUri('midia/galeria'); ?>">Fotos e Vídeos</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-6">
					<ul>
						<li><a href="<?= $this->getUri('contato'); ?>">Contato</a></li>
						<li><a href="<?= $this->getUri('conta/login'); ?>">Painel</a></li>
						<li><a href="<?= $this->getUri('admin'); ?>">Painel do Administrador</a></li>
						<li><a href="<?= $this->getUri('sobre'); ?>">Sobre o UTFPR Eventos</a></li>
					</ul>
				</div>
			</div>
			<div id="footer-links2" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
				<a href="http://www.utfpr.edu.br/guarapuava" target="blank"><div class="utfpr-link col-xs-2" data-toggle="tooltip" data-placement="top" title="Acesse a página da UTFPR"><img src="<?php echo RESOURCES_FOLDER.'/img/utfpr.png'; ?>" alt="Site da UTFPR"/></div></a>
				<a href="http://www.facebook.com/UtfprGP" target="blank" ><div class="facebook-link col-xs-2" data-toggle="tooltip" data-placement="top" title="Curta a página da UTFPR no Facebook"></div></a>
				<a href="http://www.youtube.com/canaldaUTFPR"><div class="youtube-link col-xs-2" data-toggle="tooltip" data-placement="top" title="Inscreva-se no canal do Youtube"></div></a>
			</div>
		</div>
		<br/>
		<div class="row">
			<div id="footer-info" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
				UTFPR 2014 - Site em Desenvolvimento por Gustavo Pchek e Rodrigo Miss
			</div>
		</div>
		<br/>
	</div>
</footer>