<head>
  <meta charset="utf-8">
  <title>UTFPR Eventos</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="<?php echo RESOURCES_FOLDER.'/css/bootstrap/css/bootstrap.min.css'; ?>">

  <!-- CSS tema -->
  <link rel="stylesheet" href="<?php echo RESOURCES_FOLDER.'/css/style.css'; ?>">

  <!-- Favicon -->
  <link rel="shortcut icon" href="<?php echo RESOURCES_FOLDER.'/img/favicon.png'; ?>">

  <!-- Fancybox CSS -->
  <link rel="stylesheet" href="<?php echo RESOURCES_FOLDER.'/plugins/fancybox/jquery.fancybox.css'; ?>" type="text/css" media="screen">
  <link rel="stylesheet" href="<?php echo RESOURCES_FOLDER.'/plugins/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.7'; ?>" type="text/css">

  <!-- Nivo Slider CSS -->
  <link rel="stylesheet" href="<?php echo RESOURCES_FOLDER.'/plugins/nivo-slider/nivo-slider.css'; ?>" type="text/css">
  <link rel="stylesheet" href="<?php echo RESOURCES_FOLDER.'/plugins/nivo-slider/themes/default/default.css'; ?>" type="text/css">
</head>