<div class="row">
	<div id="header" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
	  	<div class="row logged-in">
			<div id="login-bar" class="col-borded col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12">
				<?php $participant = isset($_SESSION["participant"]) ? $_SESSION["participant"] : false; ?>
					
				<?php if ($participant) : ?>
					<?= "Bem vindo, {$participant->getName()} <br />"; ?>
					<a href="<?= createUriFor('/conta/sair')?>" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-log-out"></span> Sair</a>
					<a href="<?= createUriFor('')?>" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-user"></span> Minha Conta</a>
				<?php else : ?>		
					Bem vindo, visitante<br />
					<a href="<?= createUriFor('/conta/login')?>" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-log-in"></span> Login</a>
					<a href="<?= createUriFor('/conta/nova')?>" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-log-in"></span> Cadastro</a>
				<?php endif ?>
			</div>
		</div>
	  	<div class="row logged-in" style="display:none">
			<div id="login-bar-logged-in" class="col-borded col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12">
				enderecodeemail@servicodeemail.com<br/>
				<button type="button" class="btn btn-default btn-xs">Painel</button>
				<button type="button" class="btn btn-default btn-xs">Sair</button>
			</div>
		</div>
		<div class="row">
			<div id="title-banner" class="col-lg-2 col-lg-offset-5 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2">
				<a href="<?php echo $this->getUri() ?>"><img id="title-banner-img" src="<?php echo $this->getResource('img/title-header.png'); ?>" alt="UTFPR Eventos"/></a>
			</div>
		</div>				
	</div>
</div>