<div class="row">
  <div id="main-menu" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-menu-contents">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="main-menu-contents">
          <ul class="nav navbar-nav main-menu">
          	<li><?= createLinkTo('/', 'HOME')?></li>
            <li class="dropdown dropdown-events">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">EVENTOS</a>
              <ul class="dropdown-menu">
                <li><?= createLinkTo('/eventos/proximos', 'PRÓXIMOS EVENTOS')?></li>
                <li><?= createLinkTo('/eventos/anteriores', 'EVENTOS ANTERIORES')?></li>
              </ul>
            </li>
            <li><?= createLinkTo('/noticias/lista', 'NOTÍCIAS')?></li>
            <li><?= createLinkTo('/midia/galeria', 'FOTOS E VÍDEOS')?></li>
            <li class="dropdown dropdown-events">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">CERTIFICADOS</a>
              <ul class="dropdown-menu">
                <li><?= createLinkTo('/certificados', 'VALIDAR CERTIFICADOS')?></li>
                <li><?= createLinkTo('/conta/certificados', 'OBTER CERTIFICADOS')?></li>
              </ul>
            </li>
            <li><?= createLinkTo('/contato', 'CONTATO')?></li>
            <li><?= createLinkTo('/conta/painel', 'PAINEL')?></li>
            <li><?= createLinkTo('/sobre', 'SOBRE')?></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>