<div class="row">
	<div id="title-banner" class="col-lg-2 col-lg-offset-5 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2">
		<a href="<?php echo $this->getUri() ?>"><img id="title-banner-img" src="<?php echo $this->getResource('img/title-header.png'); ?>" alt="UTFPR Eventos"/></a>
	</div>
	<div class="col-xs-12">
		<h3>O sistema de eventos está em manutenção no momento e não pode ser acessado.</h3>
	</div>
</div>				