<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 enrollment-list" style="">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de inscrições</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;"></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<!--<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></button>-->
					<div class="col-lg-4">
					  <div class="input-group">
					    <input type="text" class="form-control">
					    <div class="input-group-btn">
					      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Procurar"><span class="glyphicon glyphicon-search"></span> <span class="caret"></span></button>
					      <ul class="dropdown-menu pull-right">
				          <li><a href="#">ID</a></li>
				          <li><a href="#">Nome</a></li>
				          <li><a href="#">Evento</a></li>
				        </ul>
					    </div>
					  </div>
					</div>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Evento</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->enrollments as $enrollment) : ?>
				<tr>				
					<td align="left"><?= $enrollment->getIdEnrollment() ?></td>
					<td align="left"><?= $enrollment->participant->getName() ?></td>
					<td align="left"><?= $enrollment->event->getName() ?></td>
					<td>
						<button class="btn btn-primary btn-sm" title="Editar"><span class="glyphicon glyphicon-edit"></span></button>
						<a href="<?= createUriFor("/admin/inscricoes/{$enrollment->getIdEnrollment()}/remover") ?>">
							<button class="btn btn-danger btn-sm" title="Excluir"><span class="glyphicon glyphicon-trash"></span></button>
						</a>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
					<select class="form-control">
						<option selected>Exibir no máximo 10 itens por página</option>
						<option>Exibir no máximo 20 itens por página</option>
						<option>Exibir no máximo 40 itens por página</option>
					</select>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?php echo $this->pagination->getPageAnchors("{$this->getUri('admin/inscricoes/lista')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>