<div class="container">
	<div class="row">
		<div id="account-edit" class="row">
			<h2>Alterar Senha</h2>
			<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
				<form method="POST" action="<?= $this->actionForm ?>">
					<div class="form-group">
						<label for="old-password" class="col-sm-3 control-label">Senha antiga</label>
						<div class="col-sm-9">
						  <input type="password" class="form-control" id="old-password" name="old-password" required/>
						</div>
					</div>

					<br><br>
					
					<div class="form-group">
						<label for="new-password" class="col-sm-3 control-label">Nova senha</label>
						<div class="col-sm-9">
						  <input type="password" class="form-control" id="new-password" name="new-password" required/>
						</div>
					</div>

					<br>

					<div class="form-group">
						<label for="new-password-repeat" class="col-sm-3 control-label">Repetir nova senha</label>
						<div class="col-sm-9">
						  <input type="password" class="form-control" id="new-password-repeat" name="new-password-repeat" required/>
						</div>
					</div>

					<br><br>

					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
						  <button type="submit" class="btn btn-default"><?= $this->titleBtnSubmit ?></button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>