<div class="row">
	<div id="content" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
		<div class="row">
			<div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-3 col-md-offset-3">
				<a href="<?= $this->getUri('conta/login'); ?>">
					<div id="login-item" class="account-icons">
						<span class="glyphicon glyphicon-log-in"></span><br/>
						<span class="account-icons-title">LOGIN</span class="account-icons-title">
					</div>
				</a>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3">
				<a href="<?= $this->getUri('conta/nova'); ?>">
					<div id="register-item" class="account-icons">
						<span class="glyphicon glyphicon-pencil"></span><br/>
						<span class="account-icons-title">CADASTRO</span class="account-icons-title">
					</div>
				</a>
			</div>
		</div>
	</div>
	<div id="account-login" class="row">
		<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-sm-offset-1">
			<form action="<?= createUriFor('/conta/login')?>" method="POST">
				<div class="left-inner-addon-group">
				    <i class="glyphicon glyphicon-envelope"></i>
				    <input type="email" name="participant[email]" class="form-control input-glyphicon" placeholder="Endereço de e-mail">
				</div>
				<br/>
				<div class="left-inner-addon-group">
				    <i class="glyphicon glyphicon-asterisk"></i>
				    <input type="password" name="participant[password]" class="form-control input-glyphicon" placeholder="Senha">
				</div>
				<br/>
				<button type="submit" class="btn btn-default btn-lg">Login</button>
			</form>
		</div>
	</div>
</div>