<div class="row">
	<div id="content" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
		<div class="row">
			<div id="account-menu" class="navbar navbar-default col-xs-12 login-menu" role="navigation">
				<div class="container">
					<ul class="nav navbar-nav account-menu">
						<li><a id="btn-account-login" href="<?= $this->getUri('conta/login')?>">LOGIN</a></li>
						<li><a id="btn-account-register" href="<?= $this->getUri('conta/nova')?>">CADASTRO</a></li>
					</ul>
       			 </div>
    		</div>
		</div>
	</div>

	<div id="account-register" class="row">
		<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
			<?php require_once "_form.phtml" ?>
		</div>
	</div>
</div>