<div class="row">
	<div class="col-xs-12 col-sm-2 col-sm-offset-5">
		<h4>ID</h4>
		<input type="number" class="form-control" value="<?=$this->enrollments->getIdEnrollment()?>" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-sm-offset-3">
		<h4>Participante</h4>
		<input type="text" class="form-control" value="<?=$this->enrollments->participant->getIdParticipant() . " - " . $this->enrollments->participant->getName()?>" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-sm-offset-3">
		<h4>Evento</h4>
		<input type="text" class="form-control" value="<?=$this->enrollments->event->getIdEvent() . " - " . $this->enrollments->event->getName()?>" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-4 col-sm-offset-4">
		<h4>Tipo do Evento</h4>
		<input type="text" class="form-control" value="<?=$this->enrollments->event->eventType->getEventType()?>" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-sm-offset-3">
		<h4><?=$this->enrollments->event->eventType->getTeacherType()?></h4>
		<input type="text" class="form-control" value="<?=$this->enrollments->event->getTeacher()?>" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-6 col-sm-offset-3">
		<h4>Local</h4>
		<input type="text" class="form-control" value="<?=$this->enrollments->event->getLocal()?>" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-sm-6 col-md-4 col-md-offset-2">
		<h4>Data de inscrição</h4>
		<input type="date" class="form-control" value="<?=$this->enrollments->getDateEnrollment("d/m/Y H:i:s")?>" disabled/>
	</div>
	<div class="col-xs-6 col-sm-6 col-md-4">
		<h4>Data de pagamento</h4>
		<input type="date" class="form-control" value="<?=($this->enrollments->getCost() > 0 ?  $this->enrollments->getDatePayment("d/m/Y H:i:s") : "Gratuíto")?>" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-2 col-sm-offset-5">
		<h4>Valor</h4>
		<input type="number" class="form-control" value="<?=$this->enrollments->getCost()?>" disabled/>
	</div>
</div>

<br/>
<a href="<?=createUriFor("/admin/inscricoes/{$this->enrollments->getIdEnrollment()}/pagamento")?>" role="button" class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> Definir como Pago</a>
<a href="<?=createUriFor("/admin/inscricoes/lista")?>" role="button" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span> Voltar</a>
<a href="<?=createUriFor("/admin/inscricoes/{$this->enrollments->getIdEnrollment()}/remover")?>" role="button" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Excluir</a>