<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 enrollment-list" style="">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de inscrições</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;"></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<!--<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></button>-->
					<div class="col-lg-4">
					  <div class="input-group">
					    <input type="text" class="form-control">
					    <div class="input-group-btn">
					      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Procurar"><span class="glyphicon glyphicon-search"></span> <span class="caret"></span></button>
					      <ul class="dropdown-menu pull-right">
				          <li><a href="#">ID</a></li>
				          <li><a href="#">Nome</a></li>
				          <li><a href="#">Evento</a></li>
				        </ul>
					    </div>
					  </div>
					</div>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Evento</th>
				<th>Status</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->enrollments as $enrollment) : ?>
				<tr>				
					<td align="left"><?= $enrollment->getIdEnrollment() ?></td>
					<td align="left"><?= $enrollment->participant->getName() ?></td>
					<td align="left"><?= $enrollment->event->getName() ?></td>
					<td align="left"><?= $enrollment->enrollmentStatus->getName() ?></td>
					<td>
						<a href="<?=createUriFor("/admin/inscricoes/{$enrollment->getIdEnrollment()}/ver")?>" role="button" class="btn btn-primary btn-sm" title="Editar"><span class="glyphicon glyphicon-edit"></span></a>
						<a href="<?= createUriFor("/admin/inscricoes/{$enrollment->getIdEnrollment()}/remover") ?>" role="button" class="btn btn-danger btn-sm" title="Excluir"><span class="glyphicon glyphicon-trash"></span>
						</a>
						<?php if ($enrollment->getDatePayment()) :?>
							<a href="<?= createUriFor("/admin/inscricoes/{$enrollment->getIdEnrollment()}/cancela-pagamento") ?>" role="button" class="btn btn-default btn-sm" title="Cancelar Pagamento"><span class="glyphicon glyphicon-usd"></span>
							</a>
						<?php else :?>
							<a href="<?= createUriFor("/admin/inscricoes/{$enrollment->getIdEnrollment()}/pagamento") ?>" role="button" class="btn btn-success btn-sm" title="Definir como Pago"><span class="glyphicon glyphicon-usd"></span>
							</a>
						<?php endif ?>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?php echo $this->pagination->getPageAnchors("{$this->getUri('admin/inscricoes/lista')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>