<div class="row">
	<div class="row">
		<div id="title-banner" class="col-lg-2 col-lg-offset-5 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2">
			<a href="index.php"><img id="title-banner-img" src="<?php echo $this->getResource('img/title-header.png'); ?>" alt="UTFPR Eventos"/></a>
		</div>
	</div>
	<div class="col-xs-12 col-sm-8 col-sm-offset-2">
		<h3>Área do Administrador</h3>
		<?php require_once "views/admin/includes/_flash.phtml"; ?>
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
				<form method="POST" action="<?= createUriFor('/admin/login')?>">
					<div class="input-group">
					  <span class="input-group-addon glyphicon glyphicon-user"></span>
					  <input type="text" name="admin[login]" class="form-control input-glyphicon" placeholder="Usuário">
					</div>
					<br/>
					<div class="input-group">
					  <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
					  <input type="password" name="admin[password]" class="form-control input-glyphicon" placeholder="Senha">
					</div>
					<br/>
					<button type="submit" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-log-in"></span> Login</button>
					<br/><br/>
					<a href="">Acessar o site <span class="glyphicon glyphicon-new-window"></span></a>
				</form>
			</div>
		</div>
	</div>
</div>
