<div class="row">
	<div class="row">
		<div id="title-banner" class="col-lg-2 col-lg-offset-5 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2">
			<a href="index.php"><img id="title-banner-img" src="<?php echo $this->getResource('img/title-header.png'); ?>" alt="UTFPR Eventos"/></a>
		</div>
	</div>
	<div class="col-xs-12 col-sm-8 col-sm-offset-2">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
				<form method="POST" action="<?= createUriFor('/admin/login')?>">
					<div id="email-group" class="left-inner-addon-group form-group">
					    <i class="glyphicon glyphicon-envelope"></i>
					    <input id="email" name="admin[email]" type="text" class="form-control input-glyphicon" placeholder="Endereço de e-mail" required>
					</div>
					<div id="email-group" class="left-inner-addon-group form-group">
					    <i class="glyphicon glyphicon-asterisk"></i>
					    <input type="password" id="password" name="admin[password]" class="form-control input-glyphicon" placeholder="Senha">
					</div>
					<br/>
					<button type="submit" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-log-in"></span> Login</button>
					<br/><br/>
					<a href="<?= createUriFor('')?>">Acessar o site <span class="glyphicon glyphicon-new-window"></span></a>
				</form>
			</div>
		</div>
	</div>
</div>
