<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 enrollment-list" style="">
	<h2>Registro de Presença</h2>
	<div class="col-xs-12 col-sm-8 col-sm-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
		    <h3 class="panel-title">Lista de inscritos (confirmados)</h3>
		  </div>
		  <div class="panel-body">
		  	<span class="glyphicon glyphicon-question-sign" style="float:right;"></span>
			</div>
			<form action="<?= $this->actionForm ?>" method="post">
				<table class="table">
					<tr>
						<th></th>
						<th>Código da Inscrição</th>
						<th>Nome</th>
					</tr>
					<?php foreach($this->attendanceList as $listItem) : ?>
						<!-- Input hidden para mandar valor para POST caso a checkbox estiver desmarcada -->
						<input type="hidden" name="enrollment[<?= $listItem->getIdEnrollment() ?>]"/>
						<tr>
							<td><input type="checkbox" name="enrollment[<?= $listItem->getIdEnrollment() ?>]"/></td>
							<td><?= $listItem->getIdEnrollment() ?></td>
							<td><?= $listItem->getParticipantName() ?></td>
						</tr>
					<?php endforeach; ?>
				</table>
				<div class="panel-footer">
					<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> Salvar</button>
					<a role="button" href="<?= createUriFor("/admin/eventos/lista") ?>" class="btn btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</a>
				</div>
			</form>
		</div>
	</div>
</div>