<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 events-list">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de colaboradores</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;" title="Cada evento obrigatoriamente precisa ter um tipo, e é nesta área que os tipos são cadastrados." data-toggle="tooltip" data-placement="left"></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<a href="<?= createUriFor('/admin/colaboradores/novo')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span> Cadastrar</button>
					</a>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Endereço Web</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->sponsors as $sponsor) : ?>
				<tr>
					<td><?= $sponsor->getIdSponsor() ?></td>
					<td><?= $sponsor->getName() ?></td>
					<td><?= $sponsor->getWebAddress() ?></td>
					<td>
						<a href="<?= createUriFor("/admin/colaboradores/{$sponsor->getIdSponsor()}/alterar") ?>">
							<button class='btn btn-primary btn-sm' title='Editar'>
								<span class='glyphicon glyphicon-edit'></span>
							</button>
						</a>
						<a href="<?= createUriFor("/admin/colaboradores/{$sponsor->getIdSponsor()}/remover") ?>">
							<button class='btn btn-danger btn-sm' title='Excluir'>
								<span class='glyphicon glyphicon-trash'></span>
							</button>
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?php echo $this->pagination->getPageAnchors("{$this->getUri('admin/colaboradores/lista')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>