<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title><?= $this->getHeadTitle() ?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
  <?php 
	  createStylesheetTag(
	    'css/bootstrap/css/bootstrap.min.css',
	    'css/jQueryUI/jquery-ui-1.9.2.custom.min.css',
	    'css/Hover-master/css/hover.css',
	    'css/style.css',
	    'css/utfpr/utfpr.css',
	    'plugins/fancybox/jquery.fancybox.css',
	    'plugins/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.7',
	    'plugins/nivo-slider/nivo-slider.css',
	    'plugins/nivo-slider/themes/default/default.css',
	    'plugins/font-awesome-4.3.0/css/font-awesome.min.css'
	  );

	  createShortCutIcon('favicon.png');
	?>
</head>
	<body>
		<div id="maintenance" class="container">			
			<?php 
				

require_once "views/utfpr/includes/_maintenance.phtml";
			?>
		</div>
	</body>
	<?php 

require_once "views/utfpr/includes/_foot.phtml";?>
</html>