<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title><?= $this->getHeadTitle() ?></title>
	<meta name="description" content="Acompanhe o cronograma e inscreva-se em eventos da UTFPR Guarapuava">
	<meta name="og:title" content="UTFPR Eventos">
	<meta name="og:description" content="Acompanhe o cronograma e inscreva-se em eventos da UTFPR Guarapuava">

	<?php 
	  createStylesheetTag(
	    'css/bootstrap/css/bootstrap.min.css',
	    'css/jQueryUI/jquery-ui-1.9.2.custom.min.css',
	    'css/Hover-master/css/hover.css',
	    'plugins/fancybox/jquery.fancybox.css',
	    'plugins/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.7',
	    'plugins/nivo-slider/nivo-slider.css',
	    'plugins/nivo-slider/themes/default/default.css',
	    'plugins/font-awesome-4.3.0/css/font-awesome.min.css',
	    'plugins/calendario/css/calendar.css',
	    'plugins/calendario/css/custom_2.css',
	    'css/style.css',
	    'css/utfpr/utfpr.css'
	  );

	  createShortCutIcon('favicon.png');
	?>
</head>
	<body id="site">
		<div class="container-fluid">			
			<?php 
				require_once "views/utfpr/includes/_header.phtml";
				require_once "views/utfpr/includes/_main-menu.phtml";
				require_once "views/utfpr/includes/_flash.phtml";
			?>
				<div id="main">
					<?php require_once $this->getViewPath(); ?>
				</div>
			<?php
				require_once "views/utfpr/includes/_footer.phtml";
			?>
		</div>

		<?php require_once "views/utfpr/includes/_modals.phtml";?>
	</body>

	<?php require_once "views/utfpr/includes/_foot.phtml";?>
	<script type="text/javascript">
	$(window).scroll(function() {
		if($(window).width() > 768){
			if($(window).scrollTop() >= 200 ) {
            	$("#login-bar").fadeOut();
           		$(".zoom-change").fadeOut();
	        }else{
	        	$("#login-bar").fadeIn();
	        	$(".zoom-change").fadeIn();
	        }
		}
        
    });
</script>
</html>