<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title><?= $this->getHeadTitle() ?></title>
   
  <?php 
	  createStylesheetTag(
	    'css/bootstrap/css/bootstrap.min.css',
	    'css/jQueryUI/jquery-ui-1.9.2.custom.min.css',
	    'css/Hover-master/css/hover.css',
	    //'css/style.css',
	    'css/style.css',
	    'css/utfpr/utfpr.css',
	    'plugins/fancybox/jquery.fancybox.css',
	    'plugins/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.7',
	    'plugins/nivo-slider/nivo-slider.css',
	    'plugins/nivo-slider/themes/default/default.css',
	    'plugins/font-awesome-4.3.0/css/font-awesome.min.css'
	  );

	  createShortCutIcon('favicon.png');
  ?>
</head>
	<body>
		<div class="container-fluid">			
			<?php 
				require_once "views/utfpr/includes/_header.phtml";
				require_once "views/utfpr/includes/_main-menu.phtml";
				// require_once "views/default/admin/includes/_flash.phtml";
			?>
				<div id="main">
					<?php require_once $this->getViewPath(); ?>
				</div>
			<?php
				require_once "views/utfpr/includes/_footer.phtml";
			?>
		</div>

		<?php require_once "views/utfpr/includes/_modals.phtml";?>
	</body>

	<?php require_once "views/utfpr/includes/_foot.phtml";?>
	<script type="text/javascript">
	$(window).scroll(function() {
        // once bottom of div is scrolled past
        if($('body').scrollTop() >= 200 ) {
            $("#login-bar").fadeOut();
        }else{
        	$("#login-bar").fadeIn();
        }
    });
</script>
</html>