<div class="row">
	<div class="col-xs-2 col-sm-offset-5">
		<h4>ID</h4>
		<input type="number" class="form-control" name="news[id_news]" value="" title="O ID da notícia não pode ser modificado." disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
		<h4>Destinatários (separe por vírgula)</h4>
		<input type="text" class="form-control" name="message[recipient]" value="" required/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
		<h4>Assunto (título do e-mail)</h4>
		<input type="text" class="form-control" name="message[subject]" value="" required/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
		<h4>Título</h4>
		<input type="text" class="form-control" name="message[title]" value=""/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
		<h4>Conteúdo</h4>
		<textarea id="mail-content" name="message[content]" class="form-control"></textarea>
	</div>
</div>