<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 events-list">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de tipos de participante cadastrados</h3>
	  </div>
	  <div class="panel-body">
			<div class="row">
				<div class="col-xs-12">
					<span class="label label-danger label-md"><span class="glyphicon glyphicon-warning-sign"></span> Cuidado! Alterações nesta área podem comprometer o funcionamento do sistema. <a data-toggle="modal" data-target="#system-danger-modal">Saiba mais</a>.</span>
				</div>
				<div class="col-xs-12 general-actions">
					<a href="<?= createUriFor('/admin/participantes/tipos/novo')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></button>
					</a>
					<div class="col-lg-4">
					  
					</div>
					
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Código</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->participantTypes as $participantType) : ?>
				<tr>
					<td><?= $participantType->getIdparticipantType() ?></td>
					<td><?= $participantType->getName() ?></td>
					<td><?= $participantType->getCode() ?></td>				
					<td class="actions">
						<a href="<?= createUriFor("/admin/participantes/tipos/{$participantType->getIdparticipantType()}/alterar") ?>" role="button" class='btn btn-primary btn-sm' title='Editar'>
							<span class='glyphicon glyphicon-edit'></span>
						</a>
						<a href="<?= createUriFor("/admin/participantes/tipos/{$participantType->getIdparticipantType()}/remover") ?>" role="button" class='btn btn-danger btn-sm' title='Excluir'>
							<span class='glyphicon glyphicon-trash'></span>
						</a>	
					</td>					
				</tr>
			<?php endforeach; ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?= $this->pagination->getPageAnchors("{$this->getUri('admin/participantes/tipos')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>