<div class="row">
	<div id="content" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
  	<div class="row">
  		<div id="col-right" class="col-lg-3 col-lg-push-9 col-md-3 col-md-push-9 col-sm-6 col-sm-push-6 col-xs-12">
  			<div class="row">
  				<div class="col-xs-12">
  					<?php require_once "views/includes/_search.html" ?>
  				</div>
  			</div>
  			<div class="row">
  				<div id="banner-slider" class="slider-wrapper theme-default col-xs-12">
  					<div id="slider" class="nivoSlider">
					    <a href="event-special.php"><img src="<?php echo $this->getMedia('image/banner_slider_1.png'); ?>" alt="" /></a>
					    <img src="<?php echo $this->getResource('img/placeholder-evento-2.png'); ?>" alt="" /></a>
					    <img src="<?php echo $this->getResource('img/placeholder-evento.png'); ?>" alt="" />
					    <img src="<?php echo $this->getResource('img/placeholder-evento-2.png'); ?>" alt="" />
						</div>
  				</div>
  			</div>
  		</div>
  		<div id="news-list" class="col-lg-9 col-lg-pull-3 col-md-9 col-md-pull-3 col-sm-6 col-sm-pull-6 col-xs-12">
			<div class="list-group">
			<?php foreach($this->news as $newsItem) : ?>
			  <a href="#" class="list-group-item">
			  	<div class="col-xs-3 col-sm-3 col-md-2 col-lg-2">
			  		<img class="thumbnail" src="<?=$this->getResource('img/placeholder-evento.png'); ?>" alt="...">
			  	</div>
			    <h4 class="list-group-item-heading"><?= $newsItem->getTitle()?></h4>
			    <p class="list-group-item-text"><?= $newsItem->getSubtitle()?></p>
			    <h6><?= $newsItem->getModificationDate()?></h6>
			  </a>
			<?php endforeach; ?>
			<a href="<?= $this->getUri('noticias/lista') ?>" class="older-news">Ver Notícias Anteriores</a>
			</div>
  		</div>
		</div>

		<div class="row events">
		  <div class="event col-lg-3 col-md-3 col-sm-6 col-xs-12">
		  	<a class="event-link" data-toggle="modal" data-target="#modalevent1">
			    <div class="thumbnail">
			      <img class="event-thumbnail" src="<?php echo $this->getMedia('image/event1.png'); ?>" alt="...">
			      <div class="caption">
			        <h3>Semana Acadêmica de TSI 2014</h3>
			        <p>De 22/09/14 a 26/09/14</p>
			      </div>
		    	</div>
		    </a>
		  </div>
		  <div class="event col-lg-3 col-md-3 col-sm-6 col-xs-12">
		    <a class="event-link" data-toggle="modal" data-target="#modalevent2">
		    	<div class="thumbnail">
		      <img class="event-thumbnail" src="<?php echo $this->getMedia('image/event2.jpg'); ?>" alt="...">
		      <div class="caption">
		        <h3>Semana Acadêmica EM 2014</h3>
		        <p>De 06/10/14 a 10/10/14</p>
		      </div>
		    </div>
		   </a>
		  </div>
		  <div class="event col-lg-3 col-md-3 col-sm-6 col-xs-12">
		    <a class="event-link" data-toggle="modal" data-target="#modalsubevent1">
		    	<div class="thumbnail">
		      <img class="event-thumbnail" src="<?php echo $this->getMedia('image/event1.png'); ?>" alt="...">
		      <div class="caption">
		        <h3>Minicurso de Linux</h3>
		        <p>26/09/14</p>
		      </div>
		    </div>
		   </a>
		  </div>
		  <div class="event col-lg-3 col-md-3 col-sm-6 col-xs-12">
		    <a class="event-link" data-toggle="modal" data-target="#modalevent4">
		    	<div class="thumbnail">
		      <img class="event-thumbnail" src="<?php echo $this->getResource('img/placeholder-evento-2.png'); ?>" alt="...">
		      <div class="caption">
		        <h3>Evento 4</h3>
		        <p>30/05/14</p>
		      </div>
		    </div>
		   </a>
		  </div>
		</div>
		
		<div class="row">
  		<div id="media-thumbnail" class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12"><h5>FOTOS E VÍDEOS DOS ÚLTIMOS EVENTOS</h5>
				<div class="row">
				<?php foreach($this->media as $mediaItem) : ?>
					<div class="media-item col-xs-4 col-sm-4 col-md-2 col-lg-2">
					  	<a href="<?= $mediaItem->getPath() ?>" class="fancybox" title="<?= $mediaItem->getLabel() ?>" rel="lightbox"><img class="thumbnail" src="<?= getThumbnail($mediaItem->getPath()) ?>" alt="<?= $mediaItem->getLabel() ?>"/>
						<?php if ($mediaItem->getMediaType() == 'f') : ?>
							<td><span class="glyphicon glyphicon-camera" title="Foto"></span></td>
						<?php else : ?>
							<td><span class="glyphicon glyphicon-facetime-video" title="Vídeo"></span></td>
						<?php endif; ?>
						<br/>
						<?= $mediaItem->getLabel() ?>
					  	</a>

					</div>
				<?php endforeach; ?>
				</div>
  		</div>
		</div>
	</div>
</div>