<div id="next-events">
	<h2>Próximos Eventos</h2>
	<div class="row">
		<?php $i=0;?>
		<?php foreach ($this->events as $event) : ?>
			<?php if ($i == 4) : ?>
				</div>
				<div class="row">
			<?php endif; ?>
		  <div class="event col-lg-3 col-md-3 col-sm-6 col-xs-12">
		  	<a class="event-link" data-toggle="modal" data-target="#event<?= $event->getIdEvent();?>-modal">
			    <div class="thumbnail">
			      <img class="event-thumbnail" src="<?php echo $this->getResource('img/placeholder-evento.png'); ?>" alt="...">
			      <div class="caption">
			        <h3><?= $event->getName() ?></h3>
			        <?php if ($event->getStartTime() < date("H:i") && date("H:i") < $event->getEndTime()): ?>
			        	<span class="label label-default">AGORA</span>
			        <?php elseif ($event->getStartDate() == date("d/m/Y")) : ?>
			        	<span class="label label-default">HOJE</span>
			        <?php elseif ($event->getStartDate() == $event->getEndDate()) : ?>
			        	<p> <?= $event->getStartDate() ?></p>
			        <?php else : ?>
			        	<p>De <?= $event->getStartDate() ?> a <?= $event->getStartDate() ?></p>
			        <?php endif; ?>
			      </div>
		    	</div>
		    </a>
		  </div>
		  <?php $i++;?>
		<?php endforeach; ?>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<ul class="pagination">
			  <?php echo $this->pagination->getPageAnchors("{$this->getUri('eventos/proximos')}");?>
			</ul>
		</div>
	</div>
</div>
