<div id="prev-events">
	<h2>Eventos Anteriores</h2>
	<div class="row">
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
			<?php require_once "views/includes/_search.phtml" ?>
		</div>
		<?php $i=0;?>
		<?php foreach ($this->events as $event) : ?>
			<?php if ($i == 4) : ?>
				</div>
				<div class="row">
			<?php endif; ?>
		  <div class="event col-lg-3 col-md-3 col-sm-6 col-xs-12">
		  	<a class="event-link" data-toggle="modal" data-target="#event<?= $event->getIdEvent();?>-modal">
			    <div class="thumbnail">
					<?php if ($event->getLogo()) : ?>
						<?php $image = "data:image/jpeg;base64,". base64_encode($event->getLogo()); ?>
					<?php else : ?>
						<?php $image = $this->getResource("/img/placeholder-evento.png") ?>
					<?php endif ?>
					<img class="event-thumbnail" src="<?=$image ?>" alt="<?= $event->getName() ?>">
					<div class="caption">
						<h3><?= $event->getName() ?></h3>
						<?php if ($event->getStartDate("d/m/Y") == $event->getEndDate("d/m/Y")) : ?>
							<p> <?= $event->getStartDate("d/m/Y") ?></p>
						<?php else : ?>
							<p>De <?= $event->getStartDate("d/m/Y") ?> a <?= $event->getStartDate("d/m/Y") ?></p>
						<?php endif; ?>
					</div>
		    	</div>
		    </a>
		  </div>
		  <?php $i++;?>
		<?php endforeach; ?>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<ul class="pagination">
			  <?php echo $this->pagination->getPageAnchors("{$this->getUri('eventos/anteriores')}");?>
			</ul>
		</div>
	</div>
</div>
