<div class="row">
	<div class="col-lg-8 col-md-8 col-sm-7 col-xs-12">
		<h2 class="event-title"><?= $this->events->getName() ?></h2>
		<?php if ($this->events->getStartDate() == $this->events->getEndDate()) : ?>
			<h3 class="event-date"><?= $this->events->getStartDate("d/m/Y")?></h3>
		<?php else : ?>
			<h3 class="event-date"><?= $this->events->getStartDate("d/m/Y")?> a <?= $this->events->getEndDate("d/m/Y")?></h3>
		<?php endif ?>
		<h4 class="event-address"><?= $this->events->getLocal()?></h4>
		<?php if ($this->events->isSubEvent()) : ?>
			<h3><span class="label label-info">Este evento faz parte do evento: <a class="event-related-link" href="<?= createUriFor("/eventos/{$this->events->parentEvent->getIdEvent()}/ver")?>"><?= $this->events->parentEvent->getName() ?></a></span></h3>
		<?php endif ?>
		<br/>
		<p class="event-short-description"></p>
	</div>
	<div class="col-bordered col-lg-4 col-md-4 col-sm-5 col-xs-12">
		<?php if ($media = $this->events->getMedia()) : ?>
			<?php $media = $media[0] ?>
			<?php $image = $this->getMedia("/image/{$media->getPath()}") ?>
		<?php else : ?>
			<?php $image = $this->getResource("/img/placeholder-evento.png") ?>
		<?php endif ?>
		<img class="event-thumbnail" src="<?=$image?>" alt="<?=($media ? $media->getLabel() : "")?>">
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<p class="event-long-description"><?= $this->events->getDetails()?></p>
	</div>
	<?php if ($this->events->canEnrollment()) : ?>
		<div class="col-xs-12">
			<a href="<?= createUriFor("/inscricao/evento/{$this->events->getIdEvent()}")?>"><button type="button" class="btn btn-default btn-lg">Inscrever-se</button></a>
		</div>
	<?php endif ?>
</div>
<br/><br/>

<?php if ($this->eventsRelated) : ?>
	<div class="row events">
		<h4>Eventos relacionados</h4>

		<?php foreach ($this->eventsRelated as $event) : ?>
			<div class="event col-lg-2 col-md-2 col-sm-4 col-xs-6">
				<a class="event-link" data-toggle="modal" data-target="#event<?=$event->getIdEvent()?>-modal">
				    <div class="thumbnail">
					<?php if ($media = $event->getMedia()) : ?>
						<?php $media = $media[0] ?>
						<?php $image = $this->getMedia("/image/{$media->getPath()}") ?>
					<?php else : ?>
						<?php $image = $this->getResource("/img/placeholder-evento.png") ?>
					<?php endif ?>
				      <img class="event-thumbnail" src="<?=$image?>" alt="<?= ($media ? $media->getLabel() : "")?>">
				      <div class="caption">
				        <h3><?= $event->getName()?></h3>
				        <?php if ($event->getStartDate() == $event->getEndDate()) : ?>
				        	<p><?= $event->getStartDate("d/m/Y")?></p>
				        <?php else : ?>
				        	<p>De <?= $event->getStartDate("d/m/Y")?> até <?= $event->getEndDate("d/m/Y")?></p>
				        <?php endif ?>
				      </div>
					</div>
				</a>
			</div>
		<?php endforeach ?>
	</div>
<?php endif ?>

<div class="fb-comments" data-href="<?= createUriFor("/eventos/{$this->events->getIdEvent()}/ver")?>" data-numposts="5" data-colorscheme="light"></div>