
<h2>Notícias</h2>
<div class="row">
	<div id="news-list" class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1">
		<div class="list-group">
			<?php foreach($this->news as $newsItem) : ?>
			  <a href="#" class="list-group-item">
			  	<div class="col-xs-3 col-sm-3 col-md-2 col-lg-2">
			  		<img class="thumbnail" src="<?=$this->getResource('img/placeholder-evento.png'); ?>" alt="...">
			  	</div>
			    <h4 class="list-group-item-heading"><?= $newsItem->getTitle()?></h4>
			    <p class="list-group-item-text"><?= $newsItem->getSubtitle()?></p>
			    <h6><?= $newsItem->getModificationDate()?></h6>
			  </a>
			<?php endforeach; ?>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<ul class="pagination">
		  <?php echo $this->pagination->getPageAnchors("{$this->getUri('noticias/lista')}");?>
		</ul>
	</div>
</div>
