<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 certificates-edit">
	
	<h2>Visualizar Certificado</h2>

		<div class="row">
			<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
				<ul class="list-group">
					<li class="list-group-item">Código do certificado: <b><?= $this->certificate->getCode() ?></b></li>
					<li class="list-group-item">Participante: <b><?= strtoupper($this->certificate->enrollment->participant->getName()) ?></b></li>
					<li class="list-group-item">Evento: <b><?= $this->certificate->enrollment->event->getName()?></b></li>
					<li class="list-group-item">Data: <?= strtotime($this->certificate->enrollment->event->getStartDate("d/m/Y")) != strtotime($this->certificate->enrollment->event->getEndDate("d/m/Y")) ? "Entre " . $this->certificate->enrollment->event->getStartDate("d/m/Y") . " e " . $this->certificate->enrollment->event->getEndDate("d/m/Y") : "" . $this->certificate->enrollment->event->getStartDate("d/m/Y") ?></li>
					<li class="list-group-item">Carga horária total: <b><?= ceil((strtotime($this->certificate->enrollment->event->getEndDate("Y-m-d H:s")) - strtotime($this->certificate->enrollment->event->getStartDate("Y-m-d H:s"))) / 3600 )?> horas</b></li>
				</ul>
			</div>
		</div>

		<div class="btn-group" data-toggle="buttons">
			<label class="btn btn-material-grey active">
				<input type="radio" name="options" id="option1" autocomplete="off" checked> Template 1
			</label>
			<label class="btn btn-material-grey">
				<input type="radio" name="options" id="option2" autocomplete="off"> Template 2
			</label>
		</div>

		<?php if($this->certificate->getIdCertificate()) : ?>

			<br/>
			<br/>
			<button type="button" onclick="printDiv('certificate-view')" class="btn btn-default"><span class="glyphicon glyphicon-print"></span> Imprimir</button>
			<button type="button" class="btn btn-default" onclick="toggleTemplate()">Esconder / Exibir template</button>
			<button type="button" class="btn btn-default" onclick="toggleHeader()">Esconder / Exibir cabeçalho</button>
			<button type="button" class="btn btn-default" onclick="toggleFooter()">Esconder / Exibir rodapé</button>
			<div class="row" id="certificate-view">
				<div class="col-xs-12">
						<?php require_once "_certificate.phtml"; ?>
				</div>
			</div>
		<?php endif; ?>

	 	<br/>

		<button id="create-certificate-btn" class="btn btn-success" type="submit" disabled><span class="glyphicon glyphicon-ok-circle"></span> <?= $this->titleBtnSubmit?></button>

	<a href="<?= createUriFor('/admin/certificados')?>" role="button" class="btn btn-warning">
		<span class="glyphicon glyphicon-arrow-left"></span> Retornar
	</a>
	<a href="<?= createUriFor('/admin/certificados/'.$this->certificate->getIdCertificate().'/remover')?>" role="button" class="btn btn-danger">
		<span class="glyphicon glyphicon-trash"></span> Excluir
	</a>

</div>

<script type="text/javascript">
	enrollmentsUrl = '<?=createUriFor("/admin/certificados/inscricoes/")?>';
	function toggleTemplate(){
		if ($("#show-certificate .visual").css("visibility") == "visible"){
			$("#show-certificate .visual").css("visibility", "hidden");
		}else{
			$("#show-certificate .visual").css("visibility", "visible");
		}
	}
	function toggleHeader(){
		if ($("#show-certificate #certificate-top span").css("visibility") == "visible"){
			$("#show-certificate #certificate-top span").css("visibility", "hidden");
		}else{
			$("#show-certificate #certificate-top span").css("visibility", "visible");
		}
	}
	function toggleFooter(){
		if ($("#show-certificate #certificate-bottom").css("visibility") == "visible"){
			$("#show-certificate #certificate-bottom").css("visibility", "hidden");
		}else{
			$("#show-certificate #certificate-bottom").css("visibility", "visible");
		}
	}

</script>