<div class="row">
	<h2>Painel do Usuário</h2>
	<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 admin-main">
	<div class="row">
		<div class="col-xs-6 col-sm-2 col-sm-offset-2">
			<a href="<?= $this->getUri(''); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-edit"></span>
					<label>ALTERAR DADOS</label>
				</div>
			</a>
		</div>
		<div class="col-xs-6 col-sm-2">
			<a href="<?= $this->getUri(''); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-list-alt"></span>
					<label>MINHAS INSCRIÇÕES</label>
				</div>
			</a>
		</div>
		<div class="col-xs-6 col-sm-2">
			<a href="<?= $this->getUri('conta/sair'); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-certificate"></span>
					<label>CERTIFICADOS</label>
				</div>
			</a>
		</div>
		<div class="col-xs-6 col-sm-2">
			<a href="<?= $this->getUri(''); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-log-out"></span>
					<label>LOGOUT</label>
				</div>
			</a>
		</div>
	</div>
</div>
</div>