<div class="row">
	<div class="col-xs-12">
		<h2>Lista de inscrições</h2>
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2" style="">
			<div class="panel panel-default">
			  <div class="panel-body">
			  	<h5>As inscrições pendentes devem ser pagas em até 3 dias úteis a partir do dia da inscrição, caso contrário serão canceladas.</h5>
					<div class="row">
						<div class="col-xs-12 general-actions">
							<div class="col-lg-4">
							  <div class="input-group">
							    <input type="text" class="form-control">
							    <div class="input-group-btn">
							      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Procurar"><span class="glyphicon glyphicon-search"></span> <span class="caret"></span></button>
							      <ul class="dropdown-menu pull-right">
						          <li><a href="#">Evento</a></li>
						          <li><a href="#">Status</a></li>
						        </ul>
							    </div>
							  </div>
							</div>
						</div>
					</div>
				</div>
				<table class="table">
					<tr>
						<th>ID</th>
						<th>Evento</th>
						<th>Status</th>
					</tr>
					<tr>
						<td>2</td>
						<td>Palestra teste</td>
						<td>Confirmada</td>
					</tr>
					<tr>
						<td>1</td>
						<td>Semana Acadêmica TSI 2014</td>
						<td>Aguardando pagamento</td>
					</tr>
				</table>
				<div class="panel-footer">
					<div class="row">
						<div class="col-xs-12">
							<ul class="pagination">
							  <li class="disabled"><a href="#">&laquo;</a></li>
							  <li class="active"><a href="#">1 <span class="sr-only">Atual</span></a></li>
							  <li class=""><a href="#">2</a></li>
							  <li class=""><a href="#">3</a></li>
							  <li class=""><a href="#">&raquo;</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>