<div class="row">
	<div id="content" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
		<div class="row">
			<div id="account-menu" class="navbar navbar-default col-xs-12 login-menu" role="navigation">
				<div class="container">
		          <ul class="nav navbar-nav account-menu">
		          	   	<li><a id="btn-account-login" href="<?php echo $this->getUri('conta/login'); ?>">LOGIN</a></li>
		            	<li><a id="btn-account-register" href="<?php echo $this->getUri('conta/nova'); ?>">CADASTRO</a></li>
		          </ul>
        		</div>
    		</div>
		</div>
	</div>
	<div id="account-login" class="row">
		<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-sm-offset-1">
			<form action="<?= createUriFor('/conta/login')?>" method="POST">
				<div class="input-group">
					<span class="input-group-addon glyphicon glyphicon-envelope"></span>
				  <input type="email" name="participant[email]" class="form-control input-glyphicon" placeholder="Endereço de e-mail">
				</div>
				<br/>
				<div class="input-group">
				  <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
				  <input type="password" name="participant[password]" class="form-control input-glyphicon" placeholder="Senha">
				</div>
				<br/>
				<button type="submit" class="btn btn-default btn-lg">Login</button>
			</form>
		</div>
	</div>
</div>