<!DOCTYPE html>
<html lang="pt-br">
	<?php require_once "includes/_head.phtml";?>	

	<body>
		<div class="container">			
			<?php 
				require_once "includes/_header.phtml";
				require_once "includes/_main-menu.phtml";
				require_once $this->getViewPath();
				require_once "includes/_footer.phtml";
			?>
		</div>

		<?php require_once "includes/_modals.html";?>
	</body>

	<?php require_once "includes/_foot.phtml";?>
</html>