<div class="row">
	<div id="content" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
		<h2>Contato</h2>
		<div class="row">
			<div id="contact-form" class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
				<form action="<?= $this->actionForm ?>" method="post">
					<div id="contact-name-group" class="left-inner-addon-group form-group">
					    <i class="glyphicon glyphicon-user"></i>
					    <input type="text" class="form-control input-glyphicon" placeholder="Nome" name="name" required>
					</div>
					<br/>
					<div id="contact-email-group" class="left-inner-addon-group form-group">
					    <i class="glyphicon glyphicon-envelope"></i>
					    <input type="email" class="form-control input-glyphicon" placeholder="E-mail" name="email" required>
					</div>
					<br/>
					<div id="contact-message-group" class="left-inner-addon-group form-group">
						<textarea class="form-control input-glyphicon" placeholder="Mensagem" rows="8" name="message" required></textarea>
					</div>
					<br/>
					<button type="submit" class="btn btn-default btn-lg">Enviar Mensagem</button>
				</form>
			</div>
		</div>
	</div>
</div>