<div class="row">
	<div class="col-xs-12 col-sm-2 col-sm-offset-5">
		<h4>ID</h4>
		<input type="number" class="form-control" name="media[id_media]" value="<?= $this->media->getIdMedia()?>" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
		<h4>Legenda</h4>
		<input type="text" class="form-control" name="media[label]" value="<?= $this->media->getLabel()?>"/>
	</div>
</div>
<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>ID evento</h4>

			<div class="input-group">
		    <input id="event-id" type="number" class="form-control" name="media[id_event]" value="<?= $this->media->getIdEvent()?>" required>
		    <input id="event-link" type="hidden" value="<?= createUriFor('/admin/eventos/idevento/alterar')?>"></input>
		    <div class="input-group-btn">
		      <a id="event-access" href="<?= createUriFor('/admin/eventos/lista') ?>" target="_blank" class="btn btn-default" data-toggle="tooltip" data-placement="right" title="Lista de eventos" ><span class="glyphicon glyphicon-list"></span></a>
		    </div>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
			<h4>Tipo</h4>
			<div class="input-group well well-md media-type-define" <?= $this->media->getIdMedia() ? "title='Não é possível modificar o tipo da mídia.' data-toggle='tooltip' data-placement='bottom'" : "" ?>>
					<span> Foto </span><input id="foto" type="radio" name="media[media_type]" value="p" <?= $this->media->getMediaType() == 'p' || empty($this->media->getMediaType()) ? "checked" : ""  ?> <?= $this->media->getIdMedia() ? " disabled" : "" ?>>
					<span> Vídeo </span><input id="video" type="radio" name="media[media_type]" value="v" <?= $this->media->getMediaType() == 'v' ? "checked" : "" ?> <?= $this->media->getIdMedia() ? " disabled" : "" ?>>
			</div>
		</div>
	</div>
	<div class="row">
		<div id="photo-source" class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3" <?= $this->media->getMediaType() == 'v' ? "style='display: none'" : ""  ?> <?= $this->media->getIdMedia() ? "title='Não é possível modificar a imagem.' data-toggle='tooltip' data-placement='bottom'" : "" ?>>
			<h4>Selecione a imagem</h4>
			<span class="label label-default label-sm">OBS.: Selecione uma imagem no formato JPG, PNG ou GIF</span>
			<br/><br/>
			<input type="file" name="media" accept=".jpg,.png,.gif" <?= $this->media->getIdMedia() ? " disabled" : "" ?>>
		</div>
		<div id="video-source" class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3" <?= $this->media->getMediaType() == 'p' || empty($this->media->getMediaType()) ? "style='display: none'" : ""  ?>>
			<h4>Link</h4>
			<span class="label label-default label-sm">OBS.: No momento, o sistema só suporta vídeos do Youtube</span>
			<br/><br/>
			<div class="input-group" <?= $this->media->getIdMedia() ? "title='Não é possível modificar o URL do vídeo.' data-toggle='tooltip' data-placement='bottom'" : "" ?>>
			    <input type="text" class="form-control" name="media[path]" value="<?= $this->media->getPath()?>" <?= $this->media->getIdMedia() ? "disabled" : "" ?>>
			    <div class="input-group-btn">
			      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Acessar link"><span class="glyphicon glyphicon-new-window"></span></button>
			    </div>
			  </div>
		</div>
	</div>