<div class="row">
	<div class="col-xs-12 col-sm-2 col-sm-offset-5">
		<h4>ID</h4>
		<input type="number" class="form-control" disabled/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
		<h4>Legenda</h4>
		<input type="text" class="form-control"/>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-2 col-sm-offset-5">
		<h4>ID evento</h4>

		<div class="input-group">
	    <input id="event-id" type="number" class="form-control">
	    <input id="event-link" type="hidden" value="<?= createUriFor('/admin/eventos/idevento/alterar')?>"></input>
	    <div class="input-group-btn">
	      <button id="event-access" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Acessar evento" onclick="openEvent()"><span class="glyphicon glyphicon-new-window"></span></button>
	    </div>
	  </div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
		<h4>Tipo</h4>
		<div class="input-group well well-md media-type-define">
			<span> Foto </span><input id="foto" type="radio" name="mediatype" value="photo" checked>
			<span> Vídeo </span><input id="video" type="radio" name="mediatype" value="video">
		</div>
	</div>
</div>
<div class="row">
	<div id="photo-source" class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3" style="display:none">
		<h4>Selecione a imagem</h4>
		<span class="label label-default">OBS.: Selecione uma imagem no formato JPG, PNG ou GIF</span>
		<br/><br/>
		<input type="file" accept=".jpg,.png,.gif">
	</div>
	<div id="video-source" class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3" style="display:none">
		<h4>Link</h4>
		<span class="label label-default">OBS.: No momento, o sistema só suporta vídeos do Youtube</span>
		<br/><br/>
		<div class="input-group">
		    <input type="text" class="form-control">
		    <div class="input-group-btn">
		      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Acessar link"><span class="glyphicon glyphicon-new-window"></span></button>
		    </div>
		  </div>
	</div>
</div>