<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 media-edit">
	<form action="<?= $this->actionForm ?>" method="post">
		<?php require_once "_form.phtml"; ?>
		<br/>
		<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok-circle"></span> <?= $this->titleBtnSubmit?></button>
		<a href="<?= createUriFor('/admin/media/lista')?>">
			<button class="btn btn-warning" type="button"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
		</a>
		<a href="<?= createUriFor('/admin/midia/'.$this->media->getIdMedia().'/remover')?>">
		<button class="btn btn-danger" type="button"><span class="glyphicon glyphicon-trash"></span> Excluir</button>
		</a>
	</form>
</div>