<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 media-list">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de fotos e vídeos cadastrados</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;" title="Aqui é possível gerenciar as fotos e vídeos do sistema. É possível fazer upload de fotos, porém quanto aos vídeos são aceitos apenas links do Youtube e na listagem aparecerá a miniatura do vídeo." data-toggle="tooltip" data-placement="left"></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<a href="<?= createUriFor('/admin/midia/nova')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar Mídia" style="float: left; margin-right: 10px"><span class="glyphicon glyphicon-plus-sign"></span> Cadastrar</button>
					</a>
					<a href="<?= createUriFor('/admin/midia/novas')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar Várias" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span> Cadastrar Várias</button>
					</a>
					<div class="col-lg-4">
					  <div class="input-group">
					    <input type="text" class="form-control">
					    <div class="input-group-btn">
					      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Procurar"><span class="glyphicon glyphicon-search"></span> <span class="caret"></span></button>
					      <ul class="dropdown-menu pull-right">
				          <li><a href="#">ID</a></li>
				          <li><a href="#">Nome</a></li>
				          <li><a href="#">Tipo</a></li>
				        </ul>
					    </div>
					  </div>
					</div>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<td>ID</td>
				<th>Nome</th>
				<th>Tipo</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->media as $media) : ?>
				<tr>
					<td><?= $media->getIdMedia() ?></td>
					<td><?= $media->getLabel() ?></td>
					<?php if ($media->getMediaType() == 'p') : ?>
						<td><span class="glyphicon glyphicon-camera" title="Foto"></span></td>
					<?php else : ?>
						<td><span class="glyphicon glyphicon-facetime-video" title="Vídeo"></span></td>
					<?php endif; ?>
					<td>
						<a href="<?= createUriFor("/admin/midia/{$media->getIdMedia()}/alterar") ?>">
							<button class='btn btn-primary btn-sm' title='Editar'>
								<span class='glyphicon glyphicon-edit'></span>
							</button>
						</a>
						<a href="<?= createUriFor("/admin/midia/{$media->getIdMedia()}/remover") ?>">
							<button class='btn btn-danger btn-sm' title='Excluir'>
								<span class='glyphicon glyphicon-trash'></span>
							</button>
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?php echo $this->pagination->getPageAnchors("{$this->getUri('admin/midia/lista')}");?>
					</ul>
					<br/>
				</div>
			</div>
		</div>
	</div>
</div>