<h2>Minhas Inscrições</h2>
<div class="row">
	<?php $i=0;?>
	<?php foreach ($this->enrollment as $enrollment) : ?>
		<?php if ($i == 4) : ?>
			</div>
			<div class="row">
		<?php endif; ?>
		<div class="event col-lg-3 col-md-3 col-sm-6 col-xs-12">
			<a class="event-link" href="<?=$this->getUri("conta/inscricoes/{$enrollment->getIdEnrollment()}")?>">
			    <div class="thumbnail">
			    	<?php $event = $enrollment->event ?>
					<?php if ($media = $event->getMedia()) : ?>
						<?php $media = $media[0] ?>
						<?php $image = $media->getPath() ?>
					<?php else : ?>
						<?php $image = $this->getResource("/img/placeholder-evento.png") ?>
					<?php endif ?>
					<img class="event-thumbnail" src="<?=$image?>" alt="<?=($media ? $media->getLabel() : "")?>">
					<div class="caption">
						<h3><?= $event->getName() ?></h3>
						<?php if ($event->getStartDate("d/m/Y") == date("d/m/Y")) : ?>
							<?php if (strtotime($event->getStartDate("H:i")) < strtotime(date("H:i")) && strtotime(date("H:i")) < strtotime($event->getEndDate("H:i"))): ?>
								<span class="label label-default">AGORA</span>
							<?php else : ?>
								<span class="label label-default">HOJE</span>
							<?php endif; ?>
						<?php elseif ($event->getStartDate("d/m/Y") == $event->getEndDate("d/m/Y")) : ?>
							<p> <?= $event->getStartDate("d/m/Y") ?></p>
						<?php else : ?>
							<p>De <?= $event->getStartDate("d/m/Y") ?> a <?= $event->getEndDate("d/m/Y") ?></p>
						<?php endif; ?>
						<?php if ($enrollment->getDatePayment()) : ?>
							<span class="label label-success">PAGO</span>
						<?php elseif ($enrollment->getCost() == 0) : ?>
							<span class="label label-success">GRATUÍTO</span>
						<?php else : ?>
							<span class="label label-danger">NÃO PAGO</span>
						<?php endif ?>
					</div>
				</div>
			</a>
		</div>
	  	<?php $i++;?>
	<?php endforeach; ?>
</div>
