<script type="text/javascript">
	function selectSubEvent(id, checked) {
		var sum = document.getElementById("sum");
		var costSubEvent = parseFloat(document.getElementById("costSubEvent"+id).innerHTML);
		sum.innerHTML = (checked ? parseFloat(sum.innerHTML) + costSubEvent : parseFloat(sum.innerHTML) - costSubEvent);
	}
</script>

<div class="row">
	<form method="POST" action="<?= createUriFor('/inscricao/finalizar') ?>">
	<div class="col-xs-12">
		<h2>Inscrição</h2>
		<?php $event = $this->events ?>
		<?php $costEvent = ($event->cost ? $event->cost[0]->getCostOfDay() : 0) ?>
		<?php $enablePayment = $event->eventType->getEventType() != "sem_pagamento" ?>

		<input type="hidden" name="enrollment[id_event][]" value="<?= $event->getIdEvent()?>">
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			<h4><?= $event->getName() ?></h4>
			<h4>Valor: R$ <?= number_format($costEvent, 2) ?></h4>
			<ul class="list-group" style="text-align: left">
				<?php $subEvents = $this->eventsRelated; ?>
				<?php foreach ($subEvents as $subEvent) :?>
					<?php if ($subEvent->canEnrollment()) : ?>
						<?php $enablePayment = ($enablePayment ? true : $event->eventType->getEventType() != "sem_pagamento"); ?>
						<?php $costSubEvent = ($subEvent->cost ? $subEvent->cost[0]->getCostOfDay() : 0) ?>
						<li class="list-group-item">
							<span class="badge">
								R$ <span id="costSubEvent<?=$subEvent->getIdEvent()?>">
									<?= number_format($costSubEvent, 2) ?>
								</span>
							</span>
							<input type="checkbox" name="enrollment[id_event][]" value="<?= $subEvent->getIdEvent()?>" onClick="selectSubEvent(<?=$subEvent->getIdEvent()?>, this.checked)">
							<?=$subEvent->getName() ?>
						</li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
			<h4>Total: R$ <span id="sum"><?= number_format($costEvent, 2) ?></span></h4>
		</div>		

		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			<?php if ($enablePayment) : ?>
				<h4>Método de Pagamento</h4>
				<h5>Selecione um dos métodos de pagamento a seguir</h5>
				<ul class="list-group" style="text-align: left">
					<li class="list-group-item">
						<input type="radio" name="enrollment[id_payment_type]" value="<?=$this->paymentsType[0]->getIdPaymentType()?>">
						<img class="" src="<?=$this->getResource('img/pagseguro-logo.png')?>" style="width: 20%" alt="<?=$this->paymentsType[0]->getName() ?>">
					</li>
				</ul>
			<?php else : ?>
				<h4>Evento gratuíto</h4>
			<?php endif ?>
		</div>
	</div>
	<div class="row">
		<a href="<?= $this->uriBack?>"><button type="button" class="btn btn-lg btn-default" style="width: 150px; margin-right: 10px">
			<span class="glyphicon glyphicon-arrow-left" style="font-size: 50px"></span><br/>
			Retornar
		</button></a>
		<button class="btn btn-lg btn-success" style="width: 150px; margin-left: 10px">
			<span class="glyphicon glyphicon-arrow-right" style="font-size: 50px"></span><br/>
			Finalizar
		</button>
	</div>
	</form>
</div>


