<div class="row">
	<div class="col-lg-8 col-md-8 col-sm-7 col-xs-12">
		<h2 class="event-title"><?= $this->enrollment->event->getName() ?></h2>
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
			<h4 class="event-date">Código da Inscrição: <?=$this->enrollment->getIdEnrollment()?><br>Data da Inscrição: <?= $this->enrollment->getDateEnrollment("d M Y H:i")?>h<br>
				Valor: R$ <?=number_format($this->enrollment->getCost(), 2)?>
			</h4>

			<?php if ($this->enrollment->getDatePayment()) : ?>	
				<h4><span class="label label-info">Evento pago em: <?=$this->enrollment->getDatePayment("d/m/Y")?></span></h4>
			<?php elseif ($this->enrollment->getCost() == 0) : ?>	
				<h4><span class="label label-info">Evento Gratuíto</span></h4>
			<?php else : ?>
				<h4><span class="label label-danger">Este evento ainda não foi pago! <a class="event-related-link" href="<?=$this->enrollment->getUriPayment()?>" target="_blank">Clique aqui</a> para pagar agora!</span></h4>
			<?php endif ?>
			<?php if ($this->enrollment->event->getStartDate("d/m/Y") == $this->enrollment->event->getEndDate("d/m/Y")) : ?>
				<h3 class="event-date">Data: <?= $this->enrollment->event->getStartDate("d/m/Y")?></h3>
				<?php if ($this->enrollment->event->getStartDate("H:i") == $this->enrollment->event->getEndDate("H:i")) : ?>
					<h3 class="event-date">Horário: <?= $this->enrollment->event->getStartDate("H:i")?></h3>
				<?php else : ?>
					<h3 class="event-date">Das <?= $this->enrollment->event->getStartDate("H:i")?> às <?= $this->enrollment->event->getEndDate("H:i")?></h3>
				<?php endif ?>
			<?php else : ?>
				<h3 class="event-date">Data: <?= $this->enrollment->event->getStartDate("d/m/Y")?> a <?= $this->enrollment->event->getEndDate("d/m/Y")?></h3>
			<?php endif ?>
			<h4 class="event-address">Local do evento: <?= $this->enrollment->event->getLocal()?></h4>
			<h4 class="event-address"><?=$this->enrollment->event->eventType->getTeacherType() . ": " . $this->enrollment->event->getTeacher()?></h4>
			<?php if ($this->enrollment->event->isSubEvent()) : ?>
				<h5><span class="label label-info">Este evento faz parte do evento: <a class="event-related-link" href="<?= createUriFor("/eventos/{$this->enrollment->event->parentEvent->getIdEvent()}/ver")?>"><?= $this->enrollment->event->parentEvent->getName() ?></a></span></h5>
			<?php endif ?>
		</div>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
		<?php if ($media = $this->enrollment->event->getMedia()) : ?>
			<?php $media = $media[0] ?>
			<?php $image = $media->getPath() ?>
		<?php else : ?>
			<?php $image = $this->getResource("/img/placeholder-evento.png") ?>
		<?php endif ?>
		<img class="event-thumbnail" src="<?=$image?>" alt="<?=($media ? $media->getLabel() : "")?>">
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 event-long-description">
		<?= $this->enrollment->event->getDetails()?>
	</div>
</div>

<div class="row">
	<a href="<?= $this->uriBack?>"><button type="button" class="btn btn-default" style="width: 150px; margin-right: 10px">
		<span class="glyphicon glyphicon-arrow-left" style="font-size: 50px"></span><br/>
		Retornar
	</button></a>
</div>
