<h4>Cadastro de Usuário</h4>
<form method="POST" action="<?=$this->actionForm?>">
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>ID</h4>
			<input type="number" class="form-control" value="<?=$this->administrators->getIdAdministrator()?>" disabled/>
		</div>
	</div>
	<br/>

	<div class="row">
		<div class="col-xs-12">
			<div class="input-group">
			  <span class="input-group-addon glyphicon glyphicon-user"></span>
			  <input id="name" name="admin[name]" type="text" class="form-control input-glyphicon" placeholder="Nome" value="<?=$this->administrators->getName()?>">
			</div>
		</div>
	</div>
	<br/>

	<div class="row">
		<div class="col-xs-6">
			<div class="input-group">
				<span class="input-group-addon glyphicon glyphicon-envelope"></span>
			  <input id="email" name="admin[email]" type="text" class="form-control input-glyphicon" placeholder="Endereço de e-mail" value="<?=$this->administrators->getEmail()?>">
			</div>
		</div>
		<div class="col-xs-6">
			<div class="input-group">
			  <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
			  <input id="password" name="admin[password]" type="password" class="form-control input-glyphicon" placeholder="Senha">
			</div>
		</div>
	</div>

	<br/>
	<div class="row">
		<div class="col-xs-6">
			<input id="rg" name="admin[rg]" type="text" class="form-control" placeholder="R.G." value="<?=$this->administrators->getRg()?>">
		</div>
		<div class="col-xs-6">
			<input id="cpf" name="admin[cpf]" type="text" class="form-control" placeholder="CPF" value="<?=$this->administrators->getCpf()?>">
		</div>
	</div>
	<br/>

	<div class="row">
		<div class="col-xs-6">
			<div class="input-group">
				<span class="input-group-addon glyphicon glyphicon-phone-alt"></span>
			  <input id="phone1" name="admin[phone]" type="text" class="form-control input-glyphicon" placeholder="Telefone" value="<?=$this->administrators->getPhone()?>">
			</div>
		</div>
		<div class="col-xs-6">
			<div class="input-group">
				<span class="input-group-addon glyphicon glyphicon-earphone"></span>
			  <input id="phone2" name="admin[phone2]" type="text" class="form-control input-glyphicon" placeholder="Telefone 2" value="<?=$this->administrators->getPhone2()?>">
			</div>
		</div>
	</div>
	<br>
	
	<div class="row">
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
			<h4>Nível de Administrador</h4>
			<select name="admin[id_administrator_level]" id="id_administrator_level" class="form-control">
				<?php foreach ($this->administratorLevels as $administratorLevel): ?>
					<option value="<?= $administratorLevel->getIdAdministratorLevel() ?>"><?= $administratorLevel->getTitle() ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>

	<br/>

	<br/>
	<button class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> <?=is_null($this->administrators->getIdAdministrator()) ? "Cadastrar" : "Salvar"?></button>
	<a role="button" class="btn btn-warning" href="<?=$this->getUri("admin/usuarios/lista")?>"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</a>
	<a role="button" class="btn btn-danger" href="<?=$this->getUri("admin/usuarios/{$this->administrators->getIdAdministrator()}/remover")?>"><span class="glyphicon glyphicon-trash"></span> Excluir</a>
</form>