<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 users-list" style="">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de usuários administradores cadastrados</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;" data-toggle="tooltip" data-placement="left" title="Esta área lista os usuários do painel de administração cadastrados."></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<a href="<?=$this->getUri("admin/usuarios/novo")?>" role="button" class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></a>
					<div class="col-lg-4">
					  
					</div>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>E-mail</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->administrators as $administrator) : ?>
				<tr>
					<td><?=$administrator->getIdAdministrator()?></td>
					<td align="left"><?=$administrator->getName()?></td>
					<td align="left"><?=$administrator->getEmail()?></td>
					<td>
						<a href="<?=$this->getUri("admin/usuarios/{$administrator->getIdAdministrator()}/alterar")?>" role="button" class="btn btn-primary btn-sm" title="Editar"><span class="glyphicon glyphicon-edit"></span></a>
						<a href="<?=$this->getUri("admin/usuarios/{$administrator->getIdAdministrator()}/remover")?>" role="button" class="btn btn-danger btn-sm" title="Excluir"><span class="glyphicon glyphicon-trash"></span></a>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?= $this->pagination->getPageAnchors("{$this->getUri('admin/usuarios')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>