<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 sponsors-edit">
	
	<?php require_once "_form.phtml"; ?>

	<a href="<?= createUriFor('/admin/patrocinadores/lista')?>">
		<button class="btn btn-warning" type="button"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
	</a>
	<a href="<?= createUriFor('/admin/patrocinadores/'.$this->sponsors->getIdSponsor().'/remover')?>">
		<button class="btn btn-danger" type="button"><span class="glyphicon glyphicon-trash"></span> Excluir</button>
	</a>

	</form>
</div>