<form method="POST" action="<?=$this->actionForm?>">
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>ID</h4>
			<input type="number" name="admin_level[id_administrator_level]" class="form-control" value="<?=$this->administratorLevel->getIdAdministratorLevel()?>" disabled/>
		</div>
	</div>
	<br/>

	<div class="row">
		<div class="col-xs-12">
			<h4>Título</h4>
			<input id="title" name="admin_level[title]" type="text" class="form-control input-glyphicon" value="<?=$this->administratorLevel->getTitle()?>">
		</div>
	</div>
	<br/>


	<div class="row">
		<div class="col-xs-4 col-xs-offset-4">
			<h4>Nível</h4>
			<input id="level" name="admin_level[level]" type="number" class="form-control input-glyphicon" value="<?=$this->administratorLevel->getLevel()?>">
		</div>
	</div>
	<br/>

	<br/>
	<button class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> <?=is_null($this->administratorLevel->getIdAdministratorLevel()) ? "Cadastrar" : "Salvar"?></button>
	<a role="button" class="btn btn-warning" href="<?=$this->getUri("admin/niveis/lista")?>"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</a>
	<a role="button" class="btn btn-danger" href="<?=$this->getUri("admin/niveis/{$this->administratorLevel->getIdAdministratorLevel()}/remover")?>"><span class="glyphicon glyphicon-trash"></span> Excluir</a>
</form>