<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 admin-main">
	<div class="row">
		<div class="col-xs-4 col-sm-2">
			<a class="admin-shortcut-link" href="<?= $this->getUri('admin/inscricoes/lista'); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-list-alt"></span>
					<span class="admin-shortcut-title">LISTAR ULTIMAS INSCRICOES</span class="admin-shortcut-title">
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a class="admin-shortcut-link" href="<?= $this->getUri('admin/midia/nova'); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-film"></span>
					<span class="admin-shortcut-title">UPLOAD DE FOTOS E VIDEOS</span class="admin-shortcut-title">
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a class="admin-shortcut-link" href="<?= $this->getUri('admin/noticias/nova'); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-file"></span>
					<span class="admin-shortcut-title">CADASTRAR NOTICIA</span class="admin-shortcut-title">
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a class="admin-shortcut-link" href="<?= $this->getUri('admin/eventos/lista'); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-calendar"></span>
					<span class="admin-shortcut-title">PROXIMOS EVENTOS</span class="admin-shortcut-title">
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a class="admin-shortcut-link" href="<?= $this->getUri('admin/usuarios/lista'); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-user"></span>
					<span class="admin-shortcut-title">USUARIOS CADASTRADOS</span class="admin-shortcut-title">
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a class="admin-shortcut-link" href="<?= $this->getUri('admin/config/geral'); ?>">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-wrench"></span>
					<span class="admin-shortcut-title">AJUSTES DO SISTEMA</span class="admin-shortcut-title">
				</div>
			</a>
		</div>
	</div>
</div>