<div id="help-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="event col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h2 class="modal-title">Ajuda</h2>
          <br/>
          <h5>Bem vindo ao Painel do Administrador. Aqui você pode controlar o funcionamento do Sistema de Eventos da UTFPR.</h5>
          <h4><strong>Geral</strong> <span id="help-general-button" class="help-button glyphicon glyphicon-chevron-down" onclick="openArea('general');" title="Clique para expandir"></span></h4>
          <div class="help-general" style="display:none">
            <h5>O painel do administrador é dividido em várias áreas, que podem ser acessadas pelo menu principal:</h5>
            <p><strong>Eventos</strong>: Nesta área é possível gerenciar todos os eventos do servidor. Há também a sub-área para cadastro de tipo de evento.</p>
            <p><strong>Notícias</strong>: Na área de notícias é possível cadastrar e modificar notícias referentes à eventos.</p>
            <p><strong>Usuários</strong>: Nesta área os participantes cadastrados podem ser gerenciados.</p>
            <p><strong>Mídia</strong>: Esta área é destinada ao cadastro de fotos e vídeos referentes à vídeos.</p>
            <p><strong>Inscrições</strong>: A área de inscrições permite visualizar todas as inscrições do sistema.</p>
            <p><strong>Mensagens</strong>: Nesta área é possível enviar mensagens a inscritos em eventos, além de visualizar todas as mensagens já enviadas, incluindo as automáticas.</p>
            <p><strong>Configuração</strong>: Todas as configurações do sistema que podem ser modificadas são acessíveis nesta área.</p>
            <br/>
          </div>
          <h4><strong>Ícones</strong> <span id="help-icons-button" class="help-button glyphicon glyphicon-chevron-down" onclick="openArea('icons');" title="Clique para expandir"></span></h4>
          <div class="help-icons" style="display:none">
            Para facilitar a visualização de todos os elementos de cada tela do painel do administrador são utilizados diversos ícones no lugar de textos:
            <br/><br/>
            <table class="table" style="text-align: left">
              <thead>
                
              </thead>
              <tfoot>
                
              </tfoot>
              <tbody>
                <tr>
                  <th>Elemento</th>
                  <th>Legenda</th>
                </tr>
                <tr>
                  <td><button class="btn btn-success btn-sm" title="Cadastrar" ><span class="glyphicon glyphicon-plus-sign"></span></button></td>
                  <td>Botão Adicionar/Cadastrar</td>
                </tr>
                <tr>
                  <td><button class="btn btn-primary btn-sm" title="Editar" ><span class="glyphicon glyphicon-edit"></span></button></td>
                  <td>Botão Editar</td>
                </tr>
                <tr>
                  <td><button class="btn btn-danger btn-sm" title="Excluir" ><span class="glyphicon glyphicon-trash"></span></button></td>
                  <td>Botão Excluir</td>
                </tr>
                <tr>
                  <td><button class="btn btn-sm btn-material-blue-grey" title="Preços" ><span class="glyphicon glyphicon-stats"></span></button></td>
                  <td>Botão Estatísticas</td>
                </tr>
                <tr>
                  <td><button class="btn btn-sm btn-material-brown" title="Lista de Presença" ><span class="glyphicon glyphicon-check"></span></button></td>
                  <td>Botão Lista de Presença (Apenas para Eventos)</td>
                </tr>
                <tr>
                  <td><button class="btn btn-sm btn-material-green" title="Preços" ><span class="glyphicon glyphicon-usd"></span></button></td>
                  <td>Botão Preços (Apenas para Eventos)</td>
                </tr>
                <tr>
                  <td><button class="btn btn-sm btn-material-deep-orange" title="Colaboradores" ><span class="glyphicon glyphicon-star-empty"></span></button></td>
                  <td>Botão Colaboradores (Apenas para Eventos)</td>
                </tr>
                <tr>
                  <td><button class="btn btn-sm btn-material-indigo" title="Bônus" ><span class="glyphicon glyphicon-gift"></span></button></td>
                  <td>Botão Bônus (Apenas para Eventos)</td>
                </tr>
                <tr>
                  <td><button class="btn btn-sm btn-material-deep-purple" title="Crachás" ><span class="glyphicon glyphicon-tag"></span></button></td>
                  <td>Botão Crachá (Apenas para Eventos)</td>
                </tr>
                <tr>
                  <td><span class="badge"><span class="glyphicon glyphicon-link" title="Subevento"></span></span></td>
                  <td>Este evento é um subevento</td>
                </tr>
                <tr>
                  <td><span class="glyphicon glyphicon-question-sign" title="Enquanto o mouse estiver em cima do elemento o texto de ajuda aparecerá." data-toggle="tooltip" data-placement="right"></span></td>
                  <td>Tooltip (Dica ou texto de ajuda)</td>
                </tr>
              </tbody>
            </table>
          </div>
          <h4><strong>Mensagens Flash</strong> <span id="help-flash-button" class="help-button glyphicon glyphicon-chevron-down" onclick="openArea('flash');" title="Clique para expandir"></span></h4>
          <div class="help-flash" style="display:none">
            <p>As Mensagens Flash são mensagens que informam o administrador de acontecimentos do sistema. Geralmente elas são geradas após alguma ação do admin como cadstro, edição, salvamento, exclusão, ou ainda em outros casos para alertar ou informar.</p>
            <p>Cada mensagem é escrita de uma cor diferente para facilitar a distinção. Elas podem aparecer logo abaixo do menu principal, e também na área de login.</p>
            <div class="alert alert-success">Mensagem de sucesso</div>
            <div class="alert alert-warning">Mensagem de alerta</div>
            <div class="alert alert-danger">Mensagem de erro</div>
            <div class="alert alert-info">Mensagem de informação</div>
          </div>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>
<div id="system-danger-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="event col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h2 class="modal-title">Seções Críticas</h2>
          <br/>
          <p>Áreas do sistema como configurações de <b>Métodos de Pagamento</b>, <b>Tipos de Evento</b> e <b>Status de Inscrição</b> são consideradas críticas pois podem afetar o funcionamento do sistema, já que estão diretamente ligadas à áreas funcionais do sistema.</p>
          <br/>
          <p>Um administrador geral pode ter acesso à essas áreas, porém quaisquer alterações devem ser feitas preferencialmente por um desenvolvedor.</p>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  function openArea(area){
    if ($('.help-'+ area).css('display') == 'none')
    {
      $('.help-'+ area).show('slow');
    } else {
      $('.help-'+ area).hide('slow');
    }
    $('#help-'+ area +'-button').toggleClass('glyphicon-chevron-up');
    $('#help-'+ area +'-button').toggleClass('glyphicon-chevron-down');
  }
</script>