<form action="<?= $this->actionForm?>" method="post">
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>ID</h4>
			<input type="number" class="form-control" name="event_type[id_event_type]" value="<?= $this->eventsType->getIdEventType()?>" disabled/>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
			<h4>Tipo de Evento</h4>
			<input type="text" class="form-control" name="event_type[event_type]" value="<?= $this->eventsType->getEventType()?>"/>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
			<h4>Tipo de Ministrante</h4>
			<input type="text" class="form-control" name="event_type[teacher_type]" value="<?= $this->eventsType->getTeacherType()?>"/>
		</div>
	</div>
	<br/>
	<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok-circle"></span> <?= $this->titleBtnSubmit?></button>
	<a href="<?= createUriFor('/admin/eventos/tipos')?>">
		<button class="btn btn-warning" type="button"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
	</a>
	<a href="<?= createUriFor('/admin/eventos/tipos/'.$this->eventsType->getIdEventType().'/remover')?>">
		<button class="btn btn-danger" type="button"><span class="glyphicon glyphicon-trash"></span> Excluir</button>
	</a>
</form>