<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 events-list">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de tipos de eventos cadastrados</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;" title="Cada evento obrigatoriamente precisa ter um tipo, e é nesta área que os tipos são cadastrados." data-toggle="tooltip" data-placement="left"></span>
			<div class="row">
				<div class="col-xs-12">
					<span class="label label-danger label-md"><span class="glyphicon glyphicon-warning-sign"></span> Cuidado! Alterações nesta área podem comprometer o funcionamento do sistema. <a data-toggle="modal" data-target="#system-danger-modal">Saiba mais</a>.</span>
				</div>
				<div class="col-xs-12 general-actions">
					<a href="<?= createUriFor('/admin/eventos/tipos/novo')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></button>
					</a>
					<div class="col-lg-4">
					  <div class="input-group">
					    <input type="text" class="form-control">
					    <div class="input-group-btn">
					      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Procurar"><span class="glyphicon glyphicon-search"></span> <span class="caret"></span></button>
					      <ul class="dropdown-menu pull-right">
				          <li><a href="#">ID</a></li>
				          <li><a href="#">Tipo</a></li>				          
				          <li><a href="#">Tipo Ministrante</a></li>
				        </ul>
					    </div>
					  </div>
					</div>
					<div class="" style="float:right; font-size: 10px;"><a href="" target="blank">Acessar a página PRÓXIMOS EVENTOS <span class="glyphicon glyphicon-new-window"></span></a></div><br/>
					<div class="" style="float:right; font-size: 10px;"><a href="" target="blank">Acessar a página EVENTOS ANTERIORES <span class="glyphicon glyphicon-new-window"></span></a></div>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Código</th>
				<th>Tipo</th>
				<th>Tipo Ministrante</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->eventsType as $eventType) : ?>
				<tr>
					<td><?= $eventType->getIdEventType() ?></td>
					<td><?= $eventType->getCode() ?></td>
					<td><?= $eventType->getEventType() ?></td>
					<td><?= $eventType->getTeacherType() ?></td>						
					<td>
						<a href="<?= createUriFor("/admin/eventos/tipos/{$eventType->getIdEventType()}/alterar") ?>" role="button" class='btn btn-primary btn-sm' title='Editar'>
							<span class='glyphicon glyphicon-edit'></span>
						</a>
						<a href="<?= createUriFor("/admin/eventos/tipos/{$eventType->getIdEventType()}/remover") ?>" role="button" class='btn btn-danger btn-sm' title='Excluir'>
							<span class='glyphicon glyphicon-trash'></span>
						</a>	
					</td>					
				</tr>
			<?php endforeach; ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?= $this->pagination->getPageAnchors("{$this->getUri('admin/eventos/tipos')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>