<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 events-list">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de noticias</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;" title="Cada notícia deve ser vinculada a um evento. Cada vez que um notícia for modificada, será registrada a data e hora da modificação. Os subtítulos das notícias são usados para a listagem, e o conteúdo aparecerá na página individual de cada notícia." data-toggle="tooltip" data-placement="left"></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<a href="<?= createUriFor('/admin/noticias/nova')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></button>
					</a>
					<div class="col-lg-4">
						<form id="pesquisa" method="GET" action="<?= createUriFor('/admin/noticias/lista')?>">
							<div class="input-group">
								<input type="text" id="textPesquisa" class="form-control">
									<div class="input-group-btn">
									  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Procurar"><span class="glyphicon glyphicon-search"></span> <span class="caret"></span></button>
									  <ul class="dropdown-menu pull-right">
									  <li><a href="">ID</a></li>
									  <li><a href="">Título</a></li>
									  <li><a href="">ID do Evento</a></li>
									  <li><a href="#">Data de criação</a></li>
									  <li><a href="#">Data de modificação</a></li>
									</ul>
								</div>
							</div>
						</form>
					</div>
					<div class="" style="float:right; font-size: 10px;"><a href="<?= createUriFor('/noticias/lista')?>" target="blank">Acessar a página NOTÍCIAS <span class="glyphicon glyphicon-new-window"></span></a></div><br/>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Titulo</th>
				<th>ID Evento</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->news as $newsItem) : ?>
				<tr>
					<td><?= $newsItem->getIdNews() ?></td>
					<td><?= $newsItem->getTitle() ?></td>
					<td><?= $newsItem->getIdEvent()?></td>					
					<td>
						<a href="<?= createUriFor("/admin/noticias/{$newsItem->getIdNews()}/alterar") ?>">
							<button class='btn btn-primary btn-sm' title='Editar'>
								<span class='glyphicon glyphicon-edit'></span>
							</button>
						</a>
						<a href="<?= createUriFor("/admin/noticias/{$newsItem->getIdNews()}/remover") ?>">
							<button class='btn btn-danger btn-sm' title='Excluir'>
								<span class='glyphicon glyphicon-trash'></span>
							</button>
						</a>
					</td>					
				</tr>
			<?php endforeach; ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?php echo $this->pagination->getPageAnchors("{$this->getUri('admin/noticias/lista')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>