<div id="header">
	<h3>Painel do Administrador</h3>
</div>

<div class="row">
	<div id="content" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<?php require_once "views/admin/includes/_main-menu.phtml" ?>
		
		<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 admin-main">
			<div class="row">
				<div class="col-xs-4 col-sm-2">
					<a href="">
						<div class="admin-shortcut">
							<span class="glyphicon glyphicon-list-alt"></span>
							<label>LISTAR ULTIMAS INSCRICOES</label>
						</div>
					</a>
				</div>
				<div class="col-xs-4 col-sm-2">
					<a href="">
						<div class="admin-shortcut">
							<span class="glyphicon glyphicon-film"></span>
							<label>UPLOAD DE FOTOS E VIDEOS</label>
						</div>
					</a>
				</div>
				<div class="col-xs-4 col-sm-2">
					<a href="">
						<div class="admin-shortcut">
							<span class="glyphicon glyphicon-file"></span>
							<label>CADASTRAR NOTICIA</label>
						</div>
					</a>
				</div>
				<div class="col-xs-4 col-sm-2">
					<a href="">
						<div class="admin-shortcut">
							<span class="glyphicon glyphicon-calendar"></span>
							<label>PROXIMOS EVENTOS</label>
						</div>
					</a>
				</div>
				<div class="col-xs-4 col-sm-2">
					<a href="">
						<div class="admin-shortcut">
							<span class="glyphicon glyphicon-user"></span>
							<label>USUARIOS CADASTRADOS</label>
						</div>
					</a>
				</div>
				<div class="col-xs-4 col-sm-2">
					<a href="">
						<div class="admin-shortcut">
							<span class="glyphicon glyphicon-wrench"></span>
							<label>AJUSTES DO SISTEMA</label>
						</div>
					</a>
				</div>
			</div>
		</div>

		<?php //require_once "includes/admin/events-list.php";?>
		<?php //require_once "includes/admin/event-edit.php";?>
		<?php //require_once "includes/admin/news-list.php";?>
		<?php //require_once "includes/admin/news-edit.php";?>
		<?php //require_once "includes/admin/users-list.php";?>
		<?php //require_once "includes/admin/user-edit.php";?>
		<?php //require_once "includes/admin/media-list.php";?>
		<?php //require_once "includes/admin/media-edit.php";?>
		<?php //require_once "includes/admin/config.php";?>
		<?php //require_once "includes/admin/config-template.php";?>
		<?php //require_once "includes/admin/config-banners.php";?>
		<?php //require_once "includes/admin/inscriptions-list.php";?>
		<?php //require_once "includes/admin/inscription-edit.php";?>
	</div>
</div>

<div id="footer">
	<h6>Painel do administrador - Sistema de Eventos UTFPR</h6>
</div>	