<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 admin-main">
	<div class="row">
		<div class="col-xs-4 col-sm-2">
			<a href="">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-list-alt"></span>
					<label>LISTAR ULTIMAS INSCRICOES</label>
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a href="">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-film"></span>
					<label>UPLOAD DE FOTOS E VIDEOS</label>
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a href="">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-file"></span>
					<label>CADASTRAR NOTICIA</label>
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a href="">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-calendar"></span>
					<label>PROXIMOS EVENTOS</label>
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a href="">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-user"></span>
					<label>USUARIOS CADASTRADOS</label>
				</div>
			</a>
		</div>
		<div class="col-xs-4 col-sm-2">
			<a href="">
				<div class="admin-shortcut">
					<span class="glyphicon glyphicon-wrench"></span>
					<label>AJUSTES DO SISTEMA</label>
				</div>
			</a>
		</div>
	</div>
</div>