<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 config">
	<div class="page-header">
  	<h2>Configurações Gerais</h2>
	</div>
	<h4>Manutenção</h4>
	<div class="row">
		<form action="<?= $this->actionForm ?>" method="post">
			<div class="col-xs-6 col-xs-offset-3">
				<span class="label label-success">Site Online</span>
				<br/><br/>
				<p>Ativando o modo de manutenção, todo o site (exceto o painel de administração) ficará inacessível, e uma mensagem será exibida informando a manutenção.</p>
				<br/>
				<button class="btn btn-warning">Ativar manutenção</button>
			</div>
		</form>
	</div>
	<br/>
	<h4>Título do site</h4>
	<div class="row">
		<form action="<?= $this->actionForm ?>" method="post">
			<div class="col-xs-6 col-xs-offset-3">
				<input type="hidden" name="section" value="<?= $this->configSection ?>"/>
				<input type="text" class="form-control" name="setting[value]" value="<?= $this->settings->getValue() ?>">
				<br/>
				<button type="submit" class="btn btn-default">Alterar</button>
			</div>
		</form>
	</div>
	<hr/>
</div>