<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 config">
	<div class="page-header">
  	<h2>Configurações Gerais</h2>
	</div>
	<h4>Título do site</h4>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<input type="text" class="form-control" placeholder="UTFPR Eventos">
			<br/>
			<button class="btn btn-default">Alterar</button>
		</div>
	</div>
	<hr/>
</div>