<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 news-edit">
		<h2>Relatório de Inscrições</h2>
	
		<form action="<?= $this->actionForm ?>" method="post">
		<div class="row">
			<div class="col-xs-6 col-sm-6 col-md-4 col-md-offset-2 col-lg-2 col-lg-offset-4">
				<h4>Data inicial:</h4>
				<input type="text" class="form-control" name="reports[date_from]" value="" title=""/>
			</div>
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-2">
				<h4>Data final:</h4>
				<input type="text" class="form-control" name="reports[date_to]" value="" title=""/>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6 col-sm-6 col-md-4 col-md-offset-2 col-lg-2 col-lg-offset-4">
				<h4>Horário inicial:</h4>
				<input type="text" class="form-control" name="reports[time_from]" value="" title=""/>
			</div>
			<div class="col-xs-6 col-sm-6 col-md-4 col-lg-2">
				<h4>Horário final:</h4>
				<input type="text" class="form-control" name="reports[time_to]" value="" title=""/>
			</div>
		</div>
		<br/>
		<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok-circle"></span> <?= $this->titleBtnSubmit?></button>
		<a href="<?= createUriFor('/admin/noticias/lista')?>">
			<button class="btn btn-warning" type="button"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
		</a>
	</form>
</div>