<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 user-edit" style="">
	<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
	<?php require_once "_form.phtml"; ?>
		<br/>
		<button class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> Cadastrar</button>
		<button class="btn btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
		<button class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Excluir</button>
	</div>
	<br/>
</div>