<div class="row">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				
			</div>
		</div>
		<div id="content" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
			<div class="row">
		  		<h2>Sobre o UTFPR Eventos</h2>
		  	</div>
		  	<div class="row">
		  		<p style="font-size: 16px">O Site de Eventos da UTFPR Guarapuava permite que alunos, sevidores e visitantes acessem o cronograma de eventos, realizem inscrições, visualizem galeria de fotos, e tenham acesso ao histórico de eventos participados.</p>
		  		<p></p>
		  	</div>
		  	<div class="row">
				<div class="col-xs-12 col-sm-4">
					<img src="<?= $this->getResource('img/about1.png') ?>" alt="HTML5">
				</div>
				<div class="col-xs-12 col-sm-8" style="text-align: left">
					<p>O sistema começou a ser desenvolvido no final do primeiro semestre de 2014 por dois acadêmicos do curso de Tecnologia em Sistemas para Internet: Gustavo Pchek e Rodrigo Miss.</p>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-xs-12 col-sm-9" style="text-align: right">
					<p>No começo, o desenvolvimento do sistema fazia parte do projeto integrador do 3º semestre de TSI.</p>
				</div>
				<div class="col-xs-12 col-sm-3">
					<img src="<?= $this->getResource('img/about2.png') ?>" alt="CSS3">
				</div>
			</div>
			<br>
			<div class="row">
		  		<div class="col-xs-4 col-xs-offset-2 col-sm-2 col-sm-offset-2">
		  			<img src="<?= $this->getResource('img/html5-logo.png') ?>" alt="HTML5">
		  		</div>
		  		<div class="col-xs-4 col-sm-2">
		  			<img src="<?= $this->getResource('img/css3-logo.png') ?>" alt="CSS3">
		  		</div>
		  		<div class="col-xs-4 col-xs-offset-2 col-sm-2 col-sm-offset-0">
		  			<img src="<?= $this->getResource('img/php-logo.png') ?>" alt="PHP5">
		  		</div>
		  		<div class="col-xs-4 col-sm-2">
		  			<img src="<?= $this->getResource('img/javascript-logo.png') ?>" alt="Javascript">
		  		</div>
		  	</div>
		  	<br>
			<div class="row">
				<div class="col-xs-4 col-xs-offset-2 col-sm-2 col-sm-offset-2">
		  			<img src="<?= $this->getResource('img/mysql-logo.png') ?>" alt="MySQL">
		  		</div>
		  		<div class="col-xs-4 col-sm-2">
		  			<img src="<?= $this->getResource('img/bootstrap-logo.png') ?>" alt="Bootstrap">
		  		</div>
		  		<div class="col-xs-4 col-xs-offset-2 col-sm-2 col-sm-offset-0">
		  			<img src="<?= $this->getResource('img/jquery-logo.png') ?>" alt="jQuery">
		  		</div>
		  		<div class="col-xs-4 col-sm-2">
		  			<img src="<?= $this->getResource('img/jqueryui-logo.png') ?>" alt="jQueryUI">
		  		</div>
		  	</div>	
		</div>
	</div>
</div>