<div class="row">
	<div id="content" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
  		<h2>Sobre o UTFPR Eventos</h2>

  		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">

  			<p>O Sistema de Eventos da UTFPR Guarapuava começou a ser desenvolvido no final do primeiro semestre de 2014 por dois acadêmicos do curso de Tecnologia em Sistemas para Internet: Gustavo Pchek e Rodrigo Miss.</p>

  			<p>No começo, o desenvolvimento do sistema fazia parte do projeto integrador do 3º semestre de TSI.</p>

  		</div>

	</div>
</div>