<div class="row">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				
			</div>
		</div>
		<div id="content" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
			<div class="row">
		  		<h2>Sobre o UTFPR Eventos</h2>
		  	</div>
		  	<div class="row">
				<div class="col-xs-6 col-sm-4">
					<img src="<?= $this->getResource('img/about1.png') ?>" alt="HTML5">
				</div>
				<div class="col-xs-6 col-sm-8" style="text-align: left">
					<p>O Sistema de Eventos da UTFPR Guarapuava começou a ser desenvolvido no final do primeiro semestre de 2014 por dois acadêmicos do curso de Tecnologia em Sistemas para Internet: Gustavo Pchek e Rodrigo Miss.</p>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-xs-7 col-sm-9" style="text-align: right">
					<p>No começo, o desenvolvimento do sistema fazia parte do projeto integrador do 3º semestre de TSI.</p>
				</div>
				<div class="col-xs-5 col-sm-3">
					<img src="<?= $this->getResource('img/about2.png') ?>" alt="CSS3">
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-xs-6 col-sm-4">
					<img src="<?= $this->getResource('img/about3.png') ?>" alt="HTML5">
				</div>
				<div class="col-xs-6 col-sm-8" style="text-align: left">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque odio quis ab quisquam deleniti doloremque, harum, et porro expedita consequatur numquam praesentium, enim accusantium? Rem hic quod ullam labore perferendis.</p>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-xs-8 col-sm-10" style="text-align: right">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio illum provident, aperiam minima repellendus, blanditiis dolor pariatur sunt veritatis hic sed, nulla maxime? Sapiente ipsum, dolore id praesentium odit, eum?</p>
				</div>
				<div class="col-xs-4 col-sm-2">
					<img src="<?= $this->getResource('img/html5-logo.png') ?>" alt="CSS3">
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-xs-4 col-sm-2">
					<img src="<?= $this->getResource('img/css3-logo.png') ?>" alt="CSS3">
				</div>
				<div class="col-xs-8 col-sm-10" style="text-align: left">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed mollitia libero laudantium aut commodi eius, magni id voluptate laboriosam nemo tempora deleniti, incidunt ratione maiores pariatur sequi alias, consequatur tenetur.</p>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-xs-8 col-sm-10" style="text-align: right">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente nemo quos nam neque quod sunt veniam ratione quibusdam sed? Quaerat quos non maiores unde fugit, officia tempora odit eveniet totam!</p>
				</div>
				<div class="col-xs-4 col-sm-2">
					<img src="<?= $this->getResource('img/php-logo.png') ?>" alt="PHP5">
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-xs-4 col-sm-2">
					<img src="<?= $this->getResource('img/javascript-logo.png') ?>" alt="Javascript">
				</div>
				<div class="col-xs-8 col-sm-10" style="text-align: left">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas, cumque ratione dolores inventore maxime ex iusto culpa unde dicta, quae, cum tempora pariatur sunt sit non quam minima sequi consectetur.</p>
				</div>
			</div>


			<div class="row">
		  		<div class="col-xs-4 col-sm-2 col-md-1 col-md-offset-3">
		  			<img src="<?= $this->getResource('img/mysql-logo.png') ?>" alt="MySQL">
		  		</div>
		  		<div class="col-xs-4 col-sm-2 col-md-1">
		  			<img src="<?= $this->getResource('img/bootstrap-logo.png') ?>" alt="Bootstrap">
		  		</div>
		  		<div class="col-xs-4 col-sm-2 col-md-1">
		  			<img src="<?= $this->getResource('img/jquery-logo.png') ?>" alt="jQuery">
		  		</div>
		  		<div class="col-xs-4 col-sm-2 col-md-1">
		  			<img src="<?= $this->getResource('img/jqueryui-logo.png') ?>" alt="jQueryUI">
		  		</div>
		  		<div class="col-xs-4 col-sm-2 col-md-1">
		  			<img src="<?= $this->getResource('img/tinymce-logo.png') ?>" alt="TinyMCE">
		  		</div>
		  		<div class="col-xs-4 col-sm-2 col-md-1">
		  			<img src="<?= $this->getResource('img/fontawesome-logo.gif') ?>" alt="TinyMCE">
		  		</div>
		  	</div>	
		</div>
	</div>
</div>