<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 sponsors-new">
		
		<h2>Verificar Autenticidade</h2>

		<?php require_once "_form.phtml"; ?>

		<p>Para verificar a autenticidade de um certificado, você precisa ter o código único de identificação deste certificado.</p>

		<p>OBS.: O código do certificado possui 15 dígitos, e inicia com "<b>e-</b>"</p>

		<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-search"></span> <?= $this->titleBtnSubmit?></button>

		<br/>
		<br/>

		</form>
	</div>
</div>