<div id="show-badge">		
	<div id="badge-content">
		<?php foreach ($this->enrollments as $enrollment) :?>
			<div class="badgeItem">
				<div class="badge-logo-utfpr">
					<img src="<?= $this->getResource('img/utfpr-logo.gif') ?>" alt="Logo UTFPR">
				</div>
				<?php $qrcode = '/var/www/' . $this->getResource('img/qrcode/' . $enrollment->getIdEnrollment()) . '.png'?>
				<?php $relativePath = $this->getResource('img/qrcode/' . $enrollment->getIdEnrollment()) . '.png'?>

				<?php $content = 'BEGIN:BADGE-UTFPR\n'?>
				<?php $content .= 'id_participant:' . $enrollment->getIdParticipant() . '\n'?>
				<?php $content .= 'participant:' . $enrollment->participant->getName() . '\n'?>
				<?php $content .= 'id_enrollment:' . $enrollment->getIdEnrollment() . '\n'?>
				<?php $content .= 'event:' . $enrollment->event->getName() . '\n'?>
				<?php $content .= 'END:BADGE-UTFPR'?>
				<?php \QRCode::png($content, $qrcode, QR_ECLEVEL_M, 2)?>
				<img class="qrcode" src="<?= $relativePath?>" />

				<div class="badgeItemEvent"><?= $enrollment->event->getName()?></div>
				<div class="badgeItemFooter"><div><?= $enrollment->participant->getName()?></div></div>
				</div>
		<?php endforeach ?>
	</div>
</div>