<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 event-edit">
	<h2>Editar Estado de Inscrição</h2>
	<?php require_once "_form.phtml"; ?>
	<a href="<?= createUriFor('/admin/eventos/tipos/'.$this->eventsType->getIdEventType().'/remover')?>">
		<button class="btn btn-danger" type="button"><span class="glyphicon glyphicon-trash"></span> Excluir</button>
	</a>
</form>
</div>