<header>
	<div class="row logged-in">
		<div id="login-bar" class="col-borded col-lg-2 col-lg-offset-10 col-md-3 col-md-offset-3 col-sm-4 col-sm-offset-4 col-xs-6">
			<?php $participant = isset($_SESSION["participant"]) ? $_SESSION["participant"] : false; ?>
				
			<?php if ($participant) : ?>
				<?= "Bem vindo, {$participant->getName()} <br />"; ?>
				<a href="<?= createUriFor('/conta/painel')?>" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-user"></span> Minha Conta</a>
				<a href="<?= createUriFor('/conta/sair')?>" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-log-out"></span> Sair</a>
			<?php else : ?>		
				Bem vindo, visitante<br />
				<a class="btn btn-default btn-xs" role="button" data-toggle="modal" data-target="#login-modal"><span class="glyphicon glyphicon-log-in"></span> Login</a>
				<a href="<?= createUriFor('/conta/nova')?>" class="btn btn-default btn-xs" role="button"><span class="glyphicon glyphicon-pencil"></span> Cadastro</a>
			<?php endif ?>
			<span id="menu-arrow-down" class="help-button glyphicon glyphicon-chevron-down"></span>
		</div>
	</div>
	<div class="row" style="background-color: #2F3238">
		<div id="header" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
			<div class="row">
				<div id="title-banner" class="col-lg-2 col-lg-offset-5 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2">
					<a href="<?php echo $this->getUri() ?>"><img id="title-banner-img" src="<?php echo $this->getResource('img/utfpr/title-header.png'); ?>" alt="UTFPR Eventos"/></a>
				</div>
			</div>				
		</div>
	</div>
	<!-- <div class="container"> -->
		<div class="row zoom-change">
			<div class="col-xs-6">
				<span class="glyphicon glyphicon-zoom-in"></span>
				Aumentar zoom
			</div>
			<div class="col-xs-6">
				<span class="glyphicon glyphicon-zoom-out"></span>
				Diminuir zoom
			</div>
		</div>
	<!-- </div> -->
</header>