<div class="row">
	<div id="title-banner" class="col-lg-2 col-lg-offset-5 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2">
		<a href="<?php echo $this->getUri() ?>"><img id="title-banner-img" src="<?php echo $this->getResource('img/utfpr/title-header.png'); ?>" alt="UTFPR Eventos"/></a>
	</div>
	<div class="col-xs-12">
		<h3>O site de eventos está em manutenção no momento e não pode ser acessado.</h3>
		<br/>
	</div>
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<a href="http://www.utfpr.edu.br/guarapuava" target="blank"><div class="utfpr-link col-xs-2" data-toggle="tooltip" data-placement="top" title="Acesse a página da UTFPR"><img src="<?php echo RESOURCES_FOLDER.'/img/utfpr.png'; ?>" alt="Site da UTFPR"/></div></a>
				<a href="http://www.facebook.com/UtfprGP" target="blank" ><div class="facebook-link col-xs-2" data-toggle="tooltip" data-placement="top" title="Curta a página da UTFPR no Facebook"><i class="fa fa-facebook-official fa-4x"></i></div></a>

				<a href="http://www.youtube.com/canaldaUTFPR"><div class="youtube-link col-xs-2" data-toggle="tooltip" data-placement="top" title="Inscreva-se no canal do Youtube"><i class="fa fa-youtube-square fa-4x"></i></div></a>
		</div>
	</div>
</div>				