<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 user-edit" style="">
	<div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
		<form>
			<div class="row">
				<div class="col-xs-12 col-sm-2 col-sm-offset-5">
					<h4>ID</h4>
					<input type="number" class="form-control" disabled/>
				</div>
			</div>
			<h4>Cadastro de Usuário</h4>
			<div class="row">
				<div class="col-xs-12">
					<div class="input-group">
					  <span class="input-group-addon glyphicon glyphicon-user"></span>
					  <input id="name" type="text" class="form-control input-glyphicon" placeholder="Nome">
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-6">
					<div class="input-group">
						<span class="input-group-addon glyphicon glyphicon-envelope"></span>
					  <input id="email" type="text" class="form-control input-glyphicon" placeholder="Endereço de e-mail">
					</div>
				</div>
				<div class="col-xs-6">
					<div class="input-group">
					  <span class="input-group-addon glyphicon glyphicon-asterisk"></span>
					  <input id="password" type="text" class="form-control input-glyphicon" placeholder="Senha">
					</div>
				</div>
			</div>

			<br/>
			<div class="row">
				<div class="col-xs-6">
					<input id="rg" type="text" class="form-control" placeholder="R.G.">
				</div>
				<div class="col-xs-6">
					<input id="cpf" type="text" class="form-control" placeholder="CPF">
				</div>
			</div>
			<br/>

			<div class="row">
				<div class="col-xs-6">
					<div class="input-group">
						<span class="input-group-addon glyphicon glyphicon-phone-alt"></span>
					  <input id="phone1" type="text" class="form-control input-glyphicon" placeholder="Telefone">
					</div>
				</div>
				<div class="col-xs-6">
					<div class="input-group">
						<span class="input-group-addon glyphicon glyphicon-earphone"></span>
					  <input id="phone2" type="text" class="form-control input-glyphicon" placeholder="Telefone 2">
					</div>
				</div>
			</div>
			<br/>

			<div class="row">
				<div class="col-xs-9">
					<input id="street" type="text" class="form-control" placeholder="Rua">
				</div>
				<div class="col-xs-3">
					<input id="number" type="text" class="form-control" placeholder="Número">
				</div>
			</div>

			<div class="row">
				<div class="col-xs-7">
					<input id="district" type="text" class="form-control" placeholder="Bairro">
				</div>
				<div class="col-xs-5">
					<input id="cep" type="text" class="form-control" placeholder="CEP">
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12">
					<input id="complement" type="text" class="form-control" placeholder="Complemento">
				</div>
			</div>

			<div class="row">
				<div class="col-xs-8">
					<input id="city" type="text" class="form-control" placeholder="Cidade">
				</div>
				<div class="col-xs-4">
					<select id="state" class="form-control">
						<option selected disabled>Estado</option>
					</select>
				</div>
			</div>
			<br/>
			<button class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> Cadastrar</button>
			<button class="btn btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
		</form>
	</div>
	<br/>
</div>