<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 config">
	<div class="page-header">
  	<h2>Configurações de Contato</h2>
	</div>
	<h4>E-mail para contato</h4>
	<div class="row">
		<form action="<?= $this->actionForm ?>" method="post">
			<div class="col-xs-6 col-xs-offset-3">
				<input type="email" class="form-control" name="contact_mail" value="<?= $this->settings->getValue() ?>">
				<br/>
				<button type="submit" class="btn btn-default">Alterar</button>
			</div>
		</form>
	</div>
	<hr/>
</div>