<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 enrollment-list" style="">
	<h2>Registro de Presença</h2>
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2">
			<h4>Data</h4>
			<div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4">
				<input type="date" class="form-control"/>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2">
			<h4>Evento</h4>
			<div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
				<select class="form-control">
					<option>Evento 1</option>
					<option>Evento 2</option>
					<option>Evento 3</option>
				</select>
			</div>
		</div>
	</div>
	<br/>
	<div class="col-xs-12 col-sm-8 col-sm-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
		    <h3 class="panel-title">Lista de inscritos (confirmados)</h3>
		  </div>
		  <div class="panel-body">
		  	<span class="glyphicon glyphicon-question-sign" style="float:right;"></span>
			</div>
			<table class="table">
				<tr>
					<th></th>
					<th>Código da Inscrição</th>
					<th>Nome</th>
				</tr>
				<tr>
					<td><input type="checkbox"/></td>
					<td>873</td>
					<td>Gustavo Henrique Pchek Kwaczynski</td>
				</tr>
				<tr>
					<td><input type="checkbox"/></td>
					<td>878</td>
					<td>Rodrigo Miss</td>
				</tr>
			</table>
			<div class="panel-footer">
				<button class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> Salvar</button>
				<button class="btn btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
			</div>
		</div>
	</div>
</div>