<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 enrollment-edit" style="">
	<?php require_once "_form.phtml"; ?>
	<br/>
	<button class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> Cadastrar</button>
	<button class="btn btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
	<button class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Excluir</button>
</div>