<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 enrollment-new" style="">
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>ID</h4>
			<input type="number" class="form-control" disabled/>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>ID do participante</h4>
			<div class="input-group">
		    <input type="number" class="form-control">
		    <div class="input-group-btn">
		      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Acessar participante"><span class="glyphicon glyphicon-new-window"></span></button>
		    </div>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>ID do evento</h4>
			<div class="input-group">
		    <input type="number" class="form-control">
		    <div class="input-group-btn">
		      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Acessar participante"><span class="glyphicon glyphicon-new-window"></span></button>
		    </div>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-6 col-sm-6 col-md-4 col-md-offset-2">
			<h4>Data de inscrição</h4>
			<input type="date" class="form-control"/>
		</div>
		<div class="col-xs-6 col-sm-6 col-md-4">
			<h4>Data de pagamento</h4>
			<input type="date" class="form-control"/>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
			<h4>Forma de Pagamento</h4>
			<select class="form-control">
				<option>PagSeguro</option>
			</select>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>Valor</h4>
			<input type="number" class="form-control"/>
		</div>
	</div>
	<br/>
	<button class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> Cadastrar</button>
	<button class="btn btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
</div>