<form enctype="multipart/form-data" action="<?= $this->actionForm?>" method="post">
	<div class="row">
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
			<ul class="nav nav-pills nav-justified" id="myTab" role="tablist">
			  <li class="active"><a href="#section1" role="tab" data-toggle="pill">Principal</a></li>
			  <li><a href="#section2" role="tab" data-toggle="pill">Datas, Vagas e Patrocínio</a></li>
			  <li><a href="#section3" role="tab" data-toggle="pill">Logo e Preços</a></li>
			</ul>
		</div>
	</div>
	<div class="tab-content">
		<div id="section1" class="tab-pane fade in active">
			<div class="row">
				<div class="col-xs-6 col-sm-2 col-sm-offset-4">
					<h4>ID</h4>
					<input type="number" class="form-control" name="event[id_event]" value="<?= $this->events->getIdEvent()?>" title="O ID do evento não pode ser modificado." disabled/>
				</div>
				<div class="col-xs-6 col-sm-2">
					<h4>Visualizações</h4>
					<input type="number" class="form-control" name="event[id_event]" value="<?= $this->events->getViews()?>" title="O número de visualizações não pode ser modificado." disabled/>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-4 col-sm-offset-4 col-md-2 col-md-offset-5">
					<h4>Status</h4>
					<select name="event[enabled]" class="form-control">
						<option value="1">Ativado</option>
						<option value="0" <?= $this->events->getEnabled() ? '' : 'selected' ?>>Desativado</option>
					</select>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-2 col-sm-offset-4">
					<h4>Eventos vinculados</h4>
					<div class="input-group well well-md">
						<span> Vincular evento pai </span><input id="foto" type="radio" name="media[media_type]" value="p" checked><br/>
						<span> Vincular subeventos </span><input id="video" type="radio" name="media[media_type]" value="v">
					</div>
					<br/>
					<a id="event-access" target="_blank" onclick='javascript:$(".ajax-loader").hide();' class="btn btn-default" data-toggle="modal" data-target="#event-list-modal" ><span class="glyphicon glyphicon-list"></span> Selecione os eventos</a>
				</div>
				<div class="col-xs-12 col-sm-2">
					<h4>Permitir envio de texto pelo participante</h4>
					<div class="input-group well well-md" title="Caso seja necessário, é possível ativar um campo de texto para ser preenchido durante a inscrição." data-toggle="tooltip" data-placement="bottom">
						<span> Sim </span><input id="send_data" type="radio" name="event[send_participant_data]" value="1" <?= $this->events->getSendParticipantData() ? "checked" : ""  ?>>
						<span> Não </span><input id="not_send_data" type="radio" name="event[send_participant_data]" value="0" <?= $this->events->getSendParticipantData() ? "" : "checked" ?>>
					</div>
				</div>
			</div>
			<div id="event-list-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
				<div class="modal-dialog">
			        <div class="modal-content">
			          <div class="modal-body">
			            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			            <div class="event col-lg-12 col-md-12 col-sm-12 col-xs-12">
				            <h2 class="modal-title">Lista de eventos</h2>
				            <h5>Selecione um evento para vincular. O evento atual se tornará <u>subevento</u> do evento selecionado.</h5>
				            <table class="table table-hover" id="event-list-table">
								<tr>
									<th></th>
									<th>ID</th>
									<th>Nome</th>
									<th>Tipo</th>
									<th></th>
								</tr>
								<tr>
									<td><input id="option_0" checked type="radio" name="event[id_parent_event]" value="0"/></td>
									<td><label for="option_0">0</label></td>
									<td><label for="option_0">Nenhum</label></td>
									<td><label for="option_0"></label></td>				
									<td>					
									</td>					
								</tr>
								<?php if($this->events->isSubEvent()) : ?>
									<tr class="info">
										<td><input id="option_<?= $this->events->parentEvent->getIdEvent() ?>" checked type="radio" name="event[id_parent_event]" value="<?= $this->events->parentEvent->getIdEvent() ?>"/></td>
										<td><label for="option_<?= $this->events->parentEvent->getIdEvent() ?>"><?= $this->events->parentEvent->getIdEvent() ?></label></td>
										<td><label for="option_<?= $this->events->parentEvent->getIdEvent() ?>"><?= $this->events->parentEvent->getName() ?></label></td>
										<td><label for="option_<?= $this->events->parentEvent->getIdEvent() ?>"><?= $this->events->parentEvent->eventType->getEventType()?></label></td>				
										<td>
											<a href="<?= createUriFor("/admin/eventos/{$this->events->parentEvent->getIdEvent()}/alterar") ?>" role="button" target="_blank" class='btn btn-default btn-sm' title='Acessar página do evento'>
												<span class='glyphicon glyphicon-new-window'></span>
											</a>					
										</td>					
									</tr>
								<?php endif; ?>
							</table>
							<div class="ajax-loader"></div>
							<br>
							<span class="info" style="height:15px; width: 25px; border: 1px solid gray; display: inline-block; background: #d9edf7"></span>
							<span style="font-size: 12px; margin-bottom: 3px">Anteriormente selecionado</span>
							<br/><br/>
							<button id="btn-load" type="button" class="btn btn-default btn-xs" onclick="loadEvents();">Carregar mais</button>
							<br/>
							<br/>
			            </div>
			            <div class="caption">
			            </div>
			            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			          </div>
			       </div>
			    </div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
					<h4>Título do Evento</h4>
					<input type="text" class="form-control" name="event[name]" value="<?= $this->events->getName()?>" required/>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
					<h4>Caminho (URL)</h4>
					<input type="text" class="form-control" name="event[path]" value="<?= $this->events->getPath()?>" title="O URL deve conter apenas letras minúsculas, números e traços (hífens), e deve ser único. Se um URL não for especificado, o sistema irá gerar um automaticamente." data-toggle="tooltip" data-placement="top"/>
					<span>EX: palestra-sobre-assunto</span>
					<span>EX2: iv-semana-academica-tsi</span>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-2">
					<h4>Tipo</h4>
					<select class="form-control" name="event[id_event_type]">
						<?php foreach ($this->eventsType as $eventType) : ?>
							<?php if (isset($this->events->eventType)) : ?>
								<?php if ($this->events->eventType->getIdEventType() == $eventType->getIdEventType()) : ?>
									<option selected value="<?=$eventType->getIdEventType()?>"><?=$eventType->getEventType()?></option>
								<?php else :?>
									<option value="<?=$eventType->getIdEventType()?>"><?=$eventType->getEventType()?></option>
								<?php endif ?>
							<?php else : ?>
								<option value="<?=$eventType->getIdEventType()?>"><?=$eventType->getEventType()?></option>
							<?php endif; ?>
						<?php endforeach ?>
					</select>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4">
					<h4>Ministrante</h4>
					<input type="text" class="form-control" name="event[teacher]" value="<?= $this->events->getTeacher()?>" required/>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
					<h4>Local</h4>
					   <input type="text" class="form-control" name="event[local]" value="<?= $this->events->getLocation()?>" required/>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
					<h4>Endereço</h4>
					<input type="text" class="form-control" name="event[address]" value="<?= $this->events->getAddress()?>" title="Digite o endereço corretamente para que o mapa possa ser exibido corretamente na página do evento. Inclua no endereço pelo menos rua, número, cidade e estado." data-toggle="tooltip" data-placement="bottom"  required/>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
					<h4>Descrição</h4>
					<h5>Nesta área insira apenas informações adicionais às preenchidas nos outros campos. Informações como local, ministrante, sub-eventos, vagas, patrocinadores, preços, datas e horários já serão exibidas na página do evento.</h5>
					<textarea id="event-content" name="event[details]"><?= $this->events->getDetails()?></textarea>
				</div>
			</div>
		</div>

		<div id="section2" class="tab-pane fade">
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
					<h4>Data e Horário do Evento</h4>
					<div class="row">
						<div class="col-xs-12 col-sm-6">
							<h5>Início</h5>
							<input type="text" class="form-control" name="event[start_date]" value="<?=$this->events->getStartDate('d/m/Y H:i')?>" maxlength="16" required/>
							<br/>
						</div>
						<div class="col-xs-12 col-sm-6">
							<h5>Fim</h5>
							<input type="text" class="form-control" name="event[end_date]" value="<?=$this->events->getEndDate('d/m/Y H:i')?>" maxlength="16" required/>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
					<h4>Data e Horário de Inscrição</h4>
					<div class="row">
						<div class="col-xs-12 col-sm-6">
							<h5>Início</h5>
							<input type="text" class="form-control" name="event[start_date_enrollment]" value="<?=$this->events->getStartDateEnrollment('d/m/Y H:i')?>" maxlength="16" required/>
						</div>
						<div class="col-xs-12 col-sm-6">
							<h5>Fim</h5>
							<input type="text" class="form-control" name="event[end_date_enrollment]" value="<?= $this->events->getEndDateEnrollment('d/m/Y H:i')?>" maxlength="16" required/>
						</div>
					</div>
				</div>
			</div>
			<br/>
			<div class="row">
				<div class="col-xs-12">
					<span class="label label-warning label-md">Alguns parâmetros do evento não poderão ser alterados após o a abertura das inscrições. <a data-toggle="modal" data-target="#date-info-modal">Saiba mais</a>.</span>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-2 col-sm-offset-5">
					<h4>Vagas</h4>
					<input type="number" min="1" class="form-control" name="event[spaces]" value="<?= $this->events->getSpaces()?>" required/>
				</div>
			</div>
			<div id="date-info-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
				<div class="modal-dialog">
			        <div class="modal-content">
			          <div class="modal-body">
			            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			            <div class="event col-lg-12 col-md-12 col-sm-12 col-xs-12">
				            <h2 class="modal-title">Edição de Evento</h2>
				            <br/>
				            <!-- <p>Após as inscrições serem abertas, os campos <b>Eventos Vinculados</b>, <b>Permitir envio de texto pelo participante</b>, <b>Tipo</b>, <b>Data e horário de <u>início</u> das inscrições</b> e não poderão ser modificados.</p> -->
				            <p>Após o <u>início</u> das inscrições, os seguintes dados <b>não poderão ser alterados</b>:</p>
				            <ul class="admin-help-list">
				            	<li>Eventos Vinculados</li>
				            	<li>Permitir envio de texto pelo participante</li>
				            	<li>Tipo</li>
				            	<li>Data e horário de <u>início</u> das inscrições</li>
				            	<li>Créditos e bônus</li>
				            </ul>
				            <br/>
				            <p>Além disso, não é possível modificar a data ou horário de <u>início</u> das inscrições para datas e horários anteriores aos atuais.</p>
				            <p>Quanto aos <b>Métodos de Pagamento</b>, nenhum poderá ser removido. Apenas adicionado.</p>
				            <p>Caso um preço já tenha entrado em vigor, ele não poderá ser modificado.</p>
				            <p>Essas restrições existem para não ocorrerem problemas com as inscrições. Portanto, é essencial configurar todos os dados do evento corretamente antes do início do período de inscrições.</p>
				            <br/>
				            <p>Além disso, nenhum evento que possuir inscrições poderá ser excluído.</p>
			            </div>
			            <div class="caption">
			            </div>
			            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			          </div>
			       </div>
			    </div>
			</div>
			<br/>
			<div class="row">
				<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
					<h4>Patrocinadores</h4>
					<select class="form-control" name="sponsors[]" size="10" multiple="multiple" title="Segure a tecla CTRL para desmarcar ou para selecionar vários patrocinadores" data-toggle="tooltip" data-placement="right">
						<?php foreach ($this->sponsors as $key => $sponsor) : ?>
							<?php if (isset($this->events->sponsorship)) : ?>
								<?php $found = false ?>
								<?php foreach ($this->events->sponsorship as $key => $sponsorship): ?>
									<?php if ($sponsorship->getIdSponsor() == $sponsor->getIdSponsor()) : ?>
										<?php $found = true ?>
										<option selected value="<?=$sponsor->getIdSponsor()?>"><?=$sponsor->getName()?></option>
									<?php endif ?>	
								<?php endforeach ?>
								<?php if(!$found) : ?>
									<option value="<?=$sponsor->getIdSponsor()?>"><?=$sponsor->getName()?></option>
								<?php endif; ?>
							<?php else : ?>
								<option value="<?=$sponsor->getIdSponsor()?>"><?=$sponsor->getName()?></option>
							<?php endif; ?>
						<?php endforeach ?>
					</select>
				</div>
			</div>
		</div>

		<div id="section3" class="tab-pane fade">
			<br/>
			<div class="row">

				<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
					<h4>Logo do evento</h4>
					<span class="label label-default">OBS.: Selecione uma imagem no formato JPG, PNG ou GIF</span>
					<br/><br/>
					<input type="file" name="logo" accept="image/jpg, image/jpeg, image/x-png, image/gif">
					<br/><br/>
					<?php if($this->events->getLogo()) : ?>
						<img src="data:image/jpeg;base64, <?= base64_encode($this->events->getLogo()) ?>" alt"<?=$this->events->getName() ?>" style="max-width: 300px" />
					<?php endif; ?>
				</div>

			</div>
			<div id="cost_event"></div>
			<br/>
			<div class="row">
				<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
					<table id="cost-table" class="table" style="background: #FFF">
						<tr>
							<th>Preço</th>
							<th>Preço válido até dia</th>
							<th><button id="cost-add_button" type="button" class="btn btn-success" data-toggle="dropdown" title="Inserir novo preço">Adicionar Preço</button></th>
						</tr>
						
						<?php if(isset($this->events->cost)) : ?>
							<?php foreach ($this->events->cost as $cost) :?>
								<tr class="cost-row">
									<input type="hidden" name="cost[id_cost_event][]" value="<?=$cost->getIdCostEvent()?>"/>
									<td><input type="number" min="0" class="form-control" name="cost[cost][]" value="<?=$cost->getCost()?>"/></td>
									<td><input type="text" class="form-control" name="cost[date_max][]" value="<?=$cost->getDateMax("d/m/Y")?>" /></td>

									<td><button type="button" class="btn btn-danger cost-delete-button"><span class="glyphicon glyphicon-trash"></span></button></td>
								
								</tr>
							<?php endforeach ?>
						<?php else : ?>
							<tr class="cost-row">
								<td><input type="hidden" name="cost[id_cost_event][]" value=""/><input type="number" min="0" class="form-control" name="cost[cost][]" value=""/></td>
								<td><input type="text" class="form-control" name="cost[date_max][]" value="" /></td>

								<td><button type="button" class="btn btn-danger cost-delete-button"><span class="glyphicon glyphicon-trash"></span></button></td>
							
							</tr>
						<?php endif; ?>
						
					</table>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-8 col-sm-offset-2">
					<h4>Tabela de Bônus</h4>
					<span class="label label-info label-md"><a data-toggle="modal" data-target="#bonus-info-modal">Saiba mais</a></span>
					<br/><br/>
				</div>
				<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
					<table id="bonus-table" class="table" style="background: #FFF">
						<tr>
							<th>Tipo de Evento</th>
							<th>Quantidade</th>
						</tr>
						<?php foreach ($this->eventsType as $key => $eventType) : ?>
							<tr>
								<td><?= $eventType->getEventType() ?><input type="hidden" name="event_bonus[id_event_type][]" value="<?= $eventType->getIdEventType() ?>"></td>
								<?php if(!empty($this->events->eventBonus)) : ?>
									<?php $foundBonus = false ?>
									<?php foreach ($this->events->eventBonus as $key => $eventBonus): ?>
										<?php if ($eventBonus->getIdEventType() == $eventType->getIdEventType()) : ?>
											<?php $foundBonus = true ?>
											<input type="hidden" name="event_bonus[id_event_bonus][]" value="<?=$eventBonus->getIdEventBonus()?>"/>
											<td><input type="number" min="0" class="form-control" name="event_bonus[quantity][]" value="<?= $eventBonus->getQuantity() ?>"></td>
										<?php endif; ?>	
									<?php endforeach ?>
									<?php if(!$foundBonus) : ?>
										<td><input type="hidden" name="event_bonus[id_event_bonus][]" value="0"/><input type="number" min="0" class="form-control" name="event_bonus[quantity][]" value="0"></td>
									<?php endif; ?>
								<?php else : ?>
									<td><input type="hidden" name="event_bonus[id_event_bonus][]" value="0"/><input type="number" min="0" class="form-control" name="event_bonus[quantity][]" value="0"></td>
								<?php endif; ?>
							</tr>
						<?php endforeach; ?>
					</table>
				</div>
			</div>
			<div id="bonus-info-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
				<div class="modal-dialog">
			        <div class="modal-content">
			          <div class="modal-body">
			            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			            <div class="event col-lg-12 col-md-12 col-sm-12 col-xs-12">
				            <h2 class="modal-title">Tabela de Bônus</h2>
				            <br/>
				            <p>Nesta tabela é possível incluir eventos bônus. Funciona da seguinte maneira: Suponhamos que você selecione, na tabela o tipo de evento "Minicurso" e o número "2". Desta forma, quando alguém se inscreve neste evento terá direito a se inscrever em 2 minicursos gratuitamente <u>que sejam eventos filhos do atual</u>.</p>
				            <p>Este recurso foi desenvolvido pensando na sua utilização em eventos como semanas acadêmicas, onde um inscrito tem direito gratuitamente a, por exemplo, 1 palestra e 1 minicurso, e caso queira participar de outros, paga os valores correspondentes.</p>
			            </div>
			            <div class="caption">
			            </div>
			            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			          </div>
			       </div>
			    </div>
			</div>
			<br/>
		</div>
	</div>
	<br>
	<br/>
	<div class="row">
		<div class="col-xs-12">
			<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok-circle"></span> <?= $this->titleBtnSubmit?></button>
			<a href="<?= createUriFor('/admin/eventos/lista')?>" class="btn btn-warning" role="button">
				<span class="glyphicon glyphicon-remove-circle"></span> Cancelar
			</a>
			<a href="<?= createUriFor('/admin/eventos/'.$this->events->getIdEvent().'/remover')?>" class="btn btn-danger" role="button">
				<span class="glyphicon glyphicon-trash"></span> Excluir
			</a>
		</div>
	</div>

</form>

<script type="text/javascript">
	page = 1;
	function loadEvents(){
		$(".ajax-loader").show();
		url = "<?=createUriFor('/admin/eventos/lista/selecao/pagina/')?>" + page;	
		$.ajax({
			url: url,
			success: function(data) {
				$("#event-list-table").children().append( data );
				//loaded = true;
				page++;
				if (/\S/.test(data) == false) {
					$("#btn-load").hide();
				}
				$(".ajax-loader").hide();
			}
		});
	}
</script>

