<script type="text/javascript">
	function pesquisa(findBy){
		document.location.href = "<?= createUriFor('/admin/eventos/lista/'); ?>" + findBy + "/" + textPesquisa.value;
	}
</script>

<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 events-list">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de eventos cadastrados</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;" title="Nesta área é possível gerenciar todos os eventos do sistema. Além de criar e editar, também é possível registrar a presença dos inscritos." data-toggle="tooltip" data-placement="left"></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<a href="<?= createUriFor('/admin/eventos/novo')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></button>
					</a>
					<div class="" style="float:right; font-size: 10px;"><a href="<?= createUriFor('/eventos/proximos')?>" target="blank">Acessar a página PRÓXIMOS EVENTOS <span class="glyphicon glyphicon-new-window"></span></a></div><br/>
					<div class="" style="float:right; font-size: 10px;"><a href="<?= createUriFor('/eventos/anteriores')?>" target="blank">Acessar a página EVENTOS ANTERIORES <span class="glyphicon glyphicon-new-window"></span></a></div>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Tipo</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->events as $event) : ?>
				<tr>
					<td align="right"><?= $event->getIdEvent() ?></td>
					<td align="left"><?= $event->getName() ?></td>
					<?php if ($event->isSubEvent()) : ?>
						<td align="left"><?= $event->eventType->getEventType() ?><span class="badge pull-right"><span class="glyphicon glyphicon-link" title="Subevento"></span></span></td>
					<?php else : ?>
						<td align="left"><?= $event->eventType->getEventType()?></td>
					<?php endif; ?>					
					<td>
						<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/estatisticas")?>" role="button" class='btn btn-default btn-material-blue-grey btn-sm' title='Acompanhar Estatísticas'>
							<span class='glyphicon glyphicon-stats'></span>
						</a>
						&nbsp;&nbsp;
						<?php if(!$event->getNoEnrollment()) : ?>							
							<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/presenca")?>" role="button" class='btn btn-sm btn-material-brown' title='Lista de Presença'>
								<span class='glyphicon glyphicon-check'></span>
							</a>
						<?php else: ?>
							<button class="btn btn-sm btn-material-grey btn-raised" title='Lista de Presença' disabled>
								<span class='glyphicon glyphicon-check'></span>
							</button>
						<?php endif; ?>
						<?php if(!$event->getFree()) : ?>
							<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/precos") ?>" role="button" class='btn btn-sm btn-material-green' title='Preços Personalizados'>
								<span class='glyphicon glyphicon-usd'></span>
							</a>
						<?php else : ?>
							<button class="btn btn-sm btn-material-grey btn-raised" title='Preços Personalizados' disabled>
								<span class='glyphicon glyphicon-usd'></span>
							</button>
						<?php endif; ?>
						<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/colaboracao") ?>" role="button" class='btn btn-primary btn-sm btn-material-deep-orange' title='Organizar Patrocínio'>
							<span class='glyphicon glyphicon-star-empty'></span>
						</a>
						<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/bonus") ?>" role="button" class='btn btn-primary btn-sm btn-material-indigo' title='Bônus de Evento'>
							<span class='glyphicon glyphicon-gift'></span>
						</a>
						&nbsp;&nbsp;		
						<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/alterar") ?>" role="button" class='btn btn-primary btn-sm' title='Editar'>
							<span class='glyphicon glyphicon-edit'></span>
						</a>	
						<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/remover") ?>" role="button" class='btn btn-danger btn-sm' title='Excluir'>
							<span class='glyphicon glyphicon-trash'></span>
						</a>
						</a>
					</td>					
				</tr>
			<?php endforeach; ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?php echo $this->pagination->getPageAnchors("{$this->getUri('admin/eventos/lista')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>