<script type="text/javascript">
	function pesquisa(findBy){
		document.location.href = "<?= createUriFor('/admin/eventos/lista/'); ?>" + findBy + "/" + textPesquisa.value;
	}
</script>

<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 events-list">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de eventos cadastrados</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;" title="Nesta área é possível gerenciar todos os eventos do sistema. Além de criar e editar, também é possível registrar a presença dos inscritos." data-toggle="tooltip" data-placement="left"></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<a href="<?= createUriFor('/admin/eventos/novo')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></button>
					</a>
					<div class="col-lg-4">
						<form id="pesquisa" method="GET" action="<?= createUriFor('/admin/eventos/lista')?>">
							<div class="input-group">
								<input type="text" id="textPesquisa" class="form-control">
									<div class="input-group-btn">
									  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Procurar"><span class="glyphicon glyphicon-search"></span> <span class="caret"></span></button>
									  <ul class="dropdown-menu pull-right">
									  <li><a href="javascript:pesquisa('id');">ID</a></li>
									  <li><a href="javascript:pesquisa('nome');">Nome</a></li>
									  <li><a href="">Tipo</a></li>
									  <li><a href="#">Data de início</a></li>
									  <li><a href="#">Data do final</a></li>
									  <li><a href="#">Ministrante</a></li>
									  <li><a href="#">Local</a></li>
									</ul>
								</div>
							</div>
						</form>
					</div>
					<div class="" style="float:right; font-size: 10px;"><a href="<?= createUriFor('/eventos/proximos')?>" target="blank">Acessar a página PRÓXIMOS EVENTOS <span class="glyphicon glyphicon-new-window"></span></a></div><br/>
					<div class="" style="float:right; font-size: 10px;"><a href="<?= createUriFor('/eventos/anteriores')?>" target="blank">Acessar a página EVENTOS ANTERIORES <span class="glyphicon glyphicon-new-window"></span></a></div>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Tipo</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->events as $event) : ?>
				<tr>
					<td align="right"><?= $event->getIdEvent() ?></td>
					<td align="left"><?= $event->getName() ?></td>
					<?php if ($event->isSubEvent()) : ?>
						<td align="left"><?= $event->eventType->getEventType() ?><span class="badge pull-right"><span class="glyphicon glyphicon-link" title="Subevento"></span></span></td>
					<?php else : ?>
						<td align="left"><?= $event->eventType->getEventType()?></td>
					<?php endif; ?>					
					<td>
							<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/estatisticas")?>" role="button" class='btn btn-default btn-sm' title='Acompanhar Estatísticas'>
								<span class='glyphicon glyphicon-stats'></span>
							</a>
						<?php if($event->eventType->getCode() != 'sem_inscricao') : ?>							
							<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/presenca")?>" role="button" class='btn btn-warning btn-sm' title='Lista de Presença'>
								<span class='glyphicon glyphicon-check'></span>
							</a>
						<?php endif; ?>
							<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/alterar") ?>" role="button" class='btn btn-primary btn-sm' title='Editar'>
								<span class='glyphicon glyphicon-edit'></span>
							</a>					
							<a href="<?= createUriFor("/admin/eventos/{$event->getIdEvent()}/remover") ?>" role="button" class='btn btn-danger btn-sm' title='Excluir'>
								<span class='glyphicon glyphicon-trash'></span>
							</a>
						</a>
					</td>					
				</tr>
			<?php endforeach; ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?php echo $this->pagination->getPageAnchors("{$this->getUri('admin/eventos/lista')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>