<div class="row">
	<div class="col-xs-12">
		<h2 class="event-title"><?= $this->event->getName() ?></h2>
	</div>
</div>

<div class="row">
	<div class='col-xs-12 <?= $this->event->getAddress() ? "col-sm-6" : "col-sm-10 col-sm-offset-1" ?>'>
		<?php if ($this->event->getLogo()) : ?>
			<div class="col-xs-10 col-xs-offset-1 <?= $this->event->getAddress() ? "col-sm-8 col-sm-offset-2" : "col-sm-4 col-sm-offset-4" ?>">
				<?php $image = "data:image/jpeg;base64,". base64_encode($this->event->getLogo()); ?>
				<img class="event-thumbnail" src="<?=$image ?>" alt="">
				<br/><br/>
			</div>
		<?php endif; ?>
		<div class="col-xs-12">
			<?php if ($this->event->getStartDate("d/m/Y") == $this->event->getEndDate("d/m/Y")) : ?>
				<h3 class="event-date">Data: <?= $this->event->getStartDate("d/m/Y")?></h3>
				<?php if ($this->event->getStartDate("H:i") == $this->event->getEndDate("H:i")) : ?>
					<h3 class="event-date">Horário: <?= $this->event->getStartDate("H:i")?></h3>
				<?php else : ?>
					<h3 class="event-date">Das <?= $this->event->getStartDate("H:i")?> às <?= $this->event->getEndDate("H:i")?></h3>
				<?php endif ?>
			<?php else : ?>
				<h3 class="event-date">Data: <?= $this->event->getStartDate("d/m/Y")?> a <?= $this->event->getEndDate("d/m/Y")?></h3>
			<?php endif ?>
			<br/>
			<span class="glyphicon glyphicon-eye-open"></span> <?= $this->event->getViews() + 1?>
			<br>
			<?php if($this->event->eventInitiated()) : ?>
				<div id="average">
					<input type="hidden" class="rating" readonly value="<?= $this->realRating ?>" data-start="0" data-stop="5" data-fractions="10"/>
				</div>
			<?php endif; ?>
			<br/>
			<?php if($this->attendance) : ?>
				<div id="participant-rating">
					<input type="hidden" class="rating-tooltip" data-start="0" data-stop="5" value="<?= $this->participantRating ?>"/>
				</div>
			<?php elseif (strtotime($this->event->getEndDate("Y-m-d")) < strtotime(date("Y-m-d"))) : ?>
				<a data-toggle="modal" data-target="#login-modal">Participou deste evento? Faça login para avaliá-lo.</a>
			<?php endif; ?>
			<br/><br/>
			<h4 class="event-enrollment-start-date">Início das inscrições: <?=$this->event->getStartDateEnrollment("d/m/Y")?> às <?= $this->event->getStartDateEnrollment("H:i")?></h4>
			<h4 class="event-enrollment-start-date">Término das inscrições: <?=$this->event->getEndDateEnrollment("d/m/Y")?> às <?= $this->event->getEndDateEnrollment("H:i")?></h4>
			<?php if ($this->event->getEndDateEnrollment("d/m/Y") == date("d/m/Y") && strtotime($this->event->getEndDateEnrollment("H:i")) > strtotime(date("H:i"))) : ?>
				<span class="label label-danger" style="font-size: 16px">Último dia!</span>
				<br/>
			<?php endif; ?>
			<br/>
			<h4 class="event-address">Local do evento: <?= $this->event->getLocation()?></h4>
			<h4 class="event-address">Endereço: <?= $this->event->getAddress()?></h4>
			<?php if ($this->event->isSubEvent()) : ?>
				<h5><span class="label label-info label-sm">Este evento faz parte do evento: <a class="event-related-link" href="<?= createUriFor("/eventos/{$this->event->parentEvent->getIdEvent()}/ver")?>"><?= $this->event->parentEvent->getName() ?></a></span></h5>
			<?php endif ?>
		</div>
	</div>
	<div class="col-sm-6 col-xs-12">
		<div class="col-xs-12 google-maps">
			<br/>
			<?php if($this->event->getAddress()) : ?>
				<iframe width="400" height="400" frameborder="0" style="border:0" src='https://www.google.com/maps/embed/v1/place?key=AIzaSyAvEa-GZOf1PMuUH4wDTg353GY5b_UIVXw&q=<?= str_replace(" ", "+", $this->event->getAddress()) ?>'></iframe>
			<?php endif; ?>
		</div>
	</div>
</div>
<div class="row">
	<br/>
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 event-long-description">
		<?= $this->event->getDetails()?>
	</div>
    <?php if ($this->event->eventType->getCode() == "sem_inscricao") : ?>
		<h4><span class="label label-info">Para participar deste evento não é necessário fazer inscrição.</span></h4>
    <?php elseif (!$this->event->eventInitiated() && $this->event->eventType->getCode() != "sem_inscricao") : ?>
		<div class="col-xs-12">
			<p>Vagas totais: <?= $this->event->getSpaces() ?></p>
			<p>Vagas restantes: <?= $this->remainingSpaces ?></p>
		</div>
		<?php if($this->isEnrolled) : ?>
			<div class="col-xs-12">
				<p>Você já se inscreveu neste evento. <a href="<?= createUriFor('/conta/inscricoes')?>">Verifique o status da inscrição</a>.</p>
			</div>
		<?php else: ?>
			<div class="col-xs-12">
				<span style="display:inline-block; margin-bottom: 20px" data-toggle="tooltip" data-placement="top" <?php echo (!$this->event->canEnrollment()?"disabled title='As inscrições abrem dia " . $this->event->getStartDateEnrollment("d/m/Y"). " às " . $this->event->getStartDateEnrollment("H:i") . ".'" : 'Inscrever-se') ?>>
				<a role="button" href="<?= createUriFor("/inscricao/evento/{$this->event->getIdEvent()}")?>" type="button" id="enroll-button" class="btn btn-default btn-lg"  <?php echo (!$this->event->canEnrollment()?"disabled" : 'Inscreva-se') ?> >Inscrever-se</a>
				</span>
			</div>
		<?php endif; ?>
	<?php endif ?>
</div>
<?php if($this->hasMedia) : ?>
	<div class="row">
		<div class="col-xs-12">
			<a role="button" href="<?= createUriFor("/midia/galeria/evento/{$this->event->getIdEvent()}")?>" type="button" id="gallery-button" class="btn btn-default btn-md"><span class="glyphicon glyphicon-picture"></span> Ver galeria</a>
		</div>
	</div>
<?php endif; ?>
<?php if ($this->sponsors) : ?>
	<div class="row">
		<?php if(count($this->sponsors) < 1) : ?>
			<h3>Colaborador</h3>
			<p><a href="<?= $this->sponsors[0]->getWebAddress() ?>"><?= $this->sponsors[0]->getName() ?></a></p>
		<?php else :?>
			<h3>Colaboradores</h3>
			<?php foreach ($this->sponsors as $key => $sponsor): ?>
				<p><a href="http://<?= $sponsor->getWebAddress() ?>"><?= $sponsor->getName() ?></a></p>
			<?php endforeach ?>
		<?php endif; ?>
	</div>
<?php endif; ?>
<?php if ($this->eventRelated) : ?>
	<br/><br/>
	<div class="row events">
		<h4>Eventos relacionados</h4>
		<?php foreach ($this->eventRelated as $event) : ?>
			<div class="event col-lg-2 col-md-2 col-sm-4 col-xs-6">
				<a class="event-link" data-toggle="modal" data-target="#event<?=$event->getIdEvent()?>-modal">
				    <div class="thumbnail">
					<?php if ($media = $event->getMedia()) : ?>
						<?php $media = $media[0] ?>
						<?php $image = $media->getPath() ?>
					<?php else : ?>
						<?php $image = $this->getResource("/img/placeholder-evento.png") ?>
					<?php endif ?>
				      <img class="event-thumbnail" src="<?=$image?>" alt="<?= ($media ? $media->getLabel() : "")?>">
				      <div class="caption">
				        <h3><?= $event->getName()?></h3>
				        <?php if ($event->getStartDate() == $event->getEndDate()) : ?>
				        	<p><?= $event->getStartDate("d/m/Y")?></p>
				        <?php else : ?>
				        	<p>De <?= $event->getStartDate("d/m/Y")?> até <?= $event->getEndDate("d/m/Y")?></p>
				        <?php endif ?>
				      </div>
					</div>
				</a>
			</div>
		<?php endforeach ?>
	</div>
<?php endif ?>
<div class="fb-comments" data-href="http://<?=$_SERVER['HTTP_HOST'] ?><?= createUriFor("/eventos/{$this->event->getIdEvent()}/ver")?>" data-numposts="5" data-colorscheme="light"></div>

<script type="text/javascript">
	ratingUrl = '<?= createUriFor("/eventos/{$this->event->getIdEvent()}/avaliacao/") ?>';
</script>