<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 media-edit">
	<form enctype="multipart/form-data" action="<?= $this->actionForm ?>" method="post">
		<?php require_once "_form.phtml"; ?>
		<br/>
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
				<?php if ($this->media->getMediaType() == 'p') : ?>
						<img src="<?=$this->media->getPath()?>" alt="<?= $this->media->getLabel() ?>"/>
				<?php else : ?>
						<img src="<?= getThumbnail($this->media->getPath()) ?>" alt="<?= $this->media->getLabel() ?>"/>
				<?php endif; ?>
			</div>
		</div>
		<br/>
		<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok-circle"></span> <?= $this->titleBtnSubmit?></button>
		<a href="<?= createUriFor('/admin/midia/lista')?>">
			<button class="btn btn-warning" type="button"><span class="glyphicon glyphicon-remove-circle"></span> Cancelar</button>
		</a>
		<a href="<?= createUriFor('/admin/midia/'.$this->media->getIdMedia().'/remover')?>">
		<button class="btn btn-danger" type="button"><span class="glyphicon glyphicon-trash"></span> Excluir</button>
		</a>
	</form>
</div>