
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
<?php
	createJavascriptTag(
			"js/jquery.min.js",
			"js/bootstrap.min.js",
			"plugins/fancybox/jquery.fancybox.pack.js",
			"plugins/fancybox/helpers/jquery.fancybox-media.js?v=1.0.6",
			"plugins/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.7",
			"plugins/nivo-slider/jquery.nivo.slider.pack.js",
			"plugins/mask/jquery.maskedinput.js",
			"js/script.js"
		);
?>
	  
	<script>
	    $(document).ready(function() {
	        $('.fancybox').fancybox({
	        	arrows : false,
	        	nextClick : true,
				helpers : {
					media : {},
					thumbs : {
						width  : 50,
						height : 50
					}
				}
			});
	    });
	</script>

	<script type="text/javascript">
	$(window).load(function() {
		$('#slider').nivoSlider({
		    effect: 'fade',               // Specify sets like: 'fold,fade,sliceDown'
		    animSpeed: 500,                 // Slide transition speed
		    pauseTime: 5000,                // How long each slide will show
		    startSlide: 0,                  // Set starting Slide (0 index)
		    directionNav: true,             // Next & Prev navigation
		    controlNav: false,               // 1,2,3... navigation
		    pauseOnHover: true,             // Stop animation while hovering
		    prevText: 'Anterior',               // Prev directionNav text
		    nextText: 'Próximo',               // Next directionNav text
		    randomStart: false,             // Start on a random slide
		});
	});
	</script>
