<div id="help-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <div class="event col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <h2 class="modal-title">Ajuda</h2>
              <br/>
              <h5>O painel do administrador é dividido em várias áreas, que podem ser acessadas pelo menu principal:</h5>
              <p><strong>Eventos</strong>: Nesta área é possível gerenciar todos os eventos do servidor. Há também a sub-área para cadastro de tipo de evento.</p>
              <p><strong>Notícias</strong>: Na área de notícias é possível cadastrar e modificar notícias referentes à eventos.</p>
              <p><strong>Usuários</strong>: Nesta área os participantes cadastrados podem ser gerenciados.</p>
              <p><strong>Mídia</strong>: Esta área é destinada ao cadastro de fotos e vídeos referentes à vídeos.</p>
              <p><strong>Inscrições</strong>: A área de inscrições permite visualizar todas as inscrições do sistema.</p>
              <p><strong>Configuração</strong>: Todas as configurações do sistema que podem ser modificadas são acessíveis nesta área.</p>
              <br/>
              <h4><strong>Ícones</strong></h4>
              Para facilitar a visualização de todos os elementos de cada tela do painel do administrador são utilizados diversos ícones no lugar de textos:
              <br/><br/>
              <table class="table" style="text-align: left">
                <thead>
                  <th>Elemento</th>
                  <th>Legenda</th>
                </thead>
                <tfoot>
                  <td></td>
                  <td></td>
                </tfoot>
                <tr>
                  <td><button class="btn btn-success btn-sm" title="Cadastrar" ><span class="glyphicon glyphicon-plus-sign"></span></button></td>
                  <td>Botão Adicionar/Cadastrar</td>
                </tr>
                <tr>
                  <td><button class="btn btn-primary btn-sm" title="Editar" ><span class="glyphicon glyphicon-edit"></span></button></td>
                  <td>Botão Deletar</td>
                </tr>
                <tr>
                  <td><button class="btn btn-danger btn-sm" title="Excluir" ><span class="glyphicon glyphicon-trash"></span></button></td>
                  <td>Botão Excluir</td>
                </tr>
                <tr>
                  <td><button class="btn btn-warning btn-sm" title="Lista de Presença" ><span class="glyphicon glyphicon-check"></span></button></td>
                  <td>Botão Lista de Presença</td>
                </tr>
                <tr>
                  <td><span class="badge"><span class="glyphicon glyphicon-link" title="Subevento"></span></span></td>
                  <td>Este evento é um subevento</td>
                </tr>
                <tr>
                  <td><span class="glyphicon glyphicon-question-sign" title="Enquanto o mouse estiver em cima do elemento o texto de ajuda aparecerá." data-toggle="tooltip" data-placement="right"></span></td>
                  <td>Tooltip (Dica ou texto de ajuda)</td>
                </tr>
              </table>
              <h4><strong>Mensagens Flash</strong></h4>
              <p>As Mensagens Flash são mensagens que informam o administrador de acontecimentos do sistema. Geralmente elas são geradas após alguma ação do admin como cadstro, edição, salvamento, exclusão, ou ainda em outros casos para alertar ou informar.</p>
              <p>Cada mensagem é escrita de uma cor diferente para facilitar a distinção. Elas podem aparecer logo abaixo do menu principal, e também na área de login.</p>
              <div class="alert alert-success">Mensagem de sucesso</div>
              <div class="alert alert-warning">Mensagem de alerta</div>
              <div class="alert alert-danger">Mensagem de erro</div>
              <div class="alert alert-info">Mensagem de informação</div>
            </div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          </div>
        </div>
      </div>
    </div>