<div class="row">
  <div id="main-menu" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a id="btn-admin-main" class="navbar-brand" href="#">UTFPR Eventos</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown dropdown-events">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Eventos</a>
              <ul class="dropdown-menu">
                <li><?= createLinkTo('/admin/events/list', '<span class="glyphicon glyphicon-list-alt"></span> Listar')?></li>
                <li><?= createLinkTo('/admin/events/new', '<span class="glyphicon glyphicon-plus"></span> Cadastrar')?></li>
              </ul>
            </li>
            <li class="dropdown dropdown-news">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Notícias</a>
              <ul class="dropdown-menu">
                <li><a id="btn-news-list" href="#"><span class="glyphicon glyphicon-list-alt"> Listar</a></li>
                <li><a id="btn-news-new" href="#"><span class="glyphicon glyphicon-plus"> Cadastrar</a></li>
              </ul>
            </li>
            <li class="dropdown dropdown-users">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuários</a>
              <ul class="dropdown-menu">
                <li><a id="btn-users-list" href="#"><span class="glyphicon glyphicon-list-alt"> Listar</a></li>
                <li><a id="btn-user-new" href="#"><span class="glyphicon glyphicon-plus"> Cadastrar</a></li>
              </ul>
            </li>
            <li class="dropdown dropdown-media">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mídia</a>
              <ul class="dropdown-menu">
                <li><a id="btn-media-list" href="#"><span class="glyphicon glyphicon-list-alt"> Listar</a></li>
                <li><a id="btn-media-new" href="#"><span class="glyphicon glyphicon-plus"> Cadastrar</a></li>
              </ul>
            </li>
            <li class="dropdown dropdown-inscriptions">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inscrições</a>
              <ul class="dropdown-menu">
                <li><a id="btn-inscriptions-list" href="#"><span class="glyphicon glyphicon-list-alt"> Listar</a></li>
                <li><a id="btn-inscription-new" href="#"><span class="glyphicon glyphicon-plus"> Cadastrar</a></li>
              </ul>
            </li>
            <li class="dropdown dropdown-config">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Configuração</a>
              <ul class="dropdown-menu">
                <li><a id="btn-config" href="#"><span class="glyphicon glyphicon-cog"></span> Configurações Gerais</a></li>
                <li><a id="btn-config-template" href="#"><span class="glyphicon glyphicon-pencil"></span> Tema e template</a></li>
                <li><a id="btn-config-banners" href="#"><span class="glyphicon glyphicon-picture"></span> Banners homepage</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <p class="navbar-text">Logado como <a href="#" class="navbar-link">Admin01</a></p>
            <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</div>