<div class="row">
  <div id="main-menu" class="col-lg-12 col-xs-12 col-sm-12 col-md-12">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a id="btn-admin-main" class="navbar-brand" href="<?= $this->getUri('admin') ?>">UTFPR Eventos</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown dropdown-events">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Eventos</a>
              <ul class="dropdown-menu">
                <li><?= createLinkTo('/admin/eventos/lista', '<span class="glyphicon glyphicon-list-alt"></span> Listar')?></li>
                <li><?= createLinkTo('/admin/eventos/novo', '<span class="glyphicon glyphicon-plus"></span> Cadastrar')?></li>
                <li><?= createLinkTo('/admin/eventos/tipos', '<span class="glyphicon glyphicon-list-alt"></span> Tipos')?></li>
              </ul>
            </li>
            <li class="dropdown dropdown-news">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Notícias</a>
              <ul class="dropdown-menu">
                <li><a id="btn-news-list" href="#"><span class="glyphicon glyphicon-list-alt"> Listar</a></li>
                <li><a id="btn-news-new" href="#"><span class="glyphicon glyphicon-plus"> Cadastrar</a></li>
              </ul>
            </li>
            <li class="dropdown dropdown-users">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Usuários</a>
              <ul class="dropdown-menu">
                <li><?= createLinkTo('/admin/usuarios/lista', '<span class="glyphicon glyphicon-list-alt"></span> Listar')?></li>
                <li><?= createLinkTo('/admin/usuarios/novo', '<span class="glyphicon glyphicon-plus"></span> Cadastrar')?></li>
              </ul>
            </li>
            <li class="dropdown dropdown-media">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mídia</a>
              <ul class="dropdown-menu">
                <li><?= createLinkTo('/admin/midia/lista', '<span class="glyphicon glyphicon-list-alt"></span> Listar')?></li>
                <li><?= createLinkTo('/admin/midia/nova', '<span class="glyphicon glyphicon-plus"></span> Cadastrar')?></li>
              </ul>
            </li>
            <li class="dropdown dropdown-inscriptions">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inscrições</a>
              <ul class="dropdown-menu">
                <li><?= createLinkTo('/admin/inscricoes/lista', '<span class="glyphicon glyphicon-list-alt"></span> Listar')?></li>
                <li><?= createLinkTo('/admin/inscricoes/nova', '<span class="glyphicon glyphicon-plus"></span> Cadastrar')?></li>
                <li><?= createLinkTo('/admin/inscricoes/presenca', '<span class="glyphicon glyphicon-check"></span> Registrar Presença')?></li>
              </ul>
            </li>
            <li class="dropdown dropdown-config">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Configuração</a>
              <ul class="dropdown-menu">
                <li><?= createLinkTo('/admin/config/geral', '<span class="glyphicon glyphicon-cog"></span> Configurações Gerais')?></li>
                <li><?= createLinkTo('/admin/config/tema', '<span class="glyphicon glyphicon-pencil"></span> Tema e template')?></li>
                <li><?= createLinkTo('/admin/config/banners', '<span class="glyphicon glyphicon-picture"></span> Banners homepage')?></li>
                <li><?= createLinkTo('/admin/config/pagamento', '<span class="glyphicon glyphicon-usd"></span> Pagamento')?></li>
                <li><?= createLinkTo('/admin/config/contato', '<span class="glyphicon glyphicon-envelope"></span> Contato')?></li>
                <li><?= createLinkTo('', '<span class="glyphicon glyphicon-user"></span> Administradores')?></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <p class="navbar-text">Logado como <a href="<?= createUriFor('/admin/logout')?>" class="navbar-link"><?= $_SESSION["admin"]->getName()?></a></p>
            <li><a href="<?= createUriFor('/admin/logout')?>"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</div>