<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title><?= $this->getHeadTitle() ?></title>
   
  <?= 
	  createStylesheetTag(
	    'css/bootstrap/css/bootstrap.min.css',
	    'css/jQueryUI/jquery-ui-1.9.2.custom.min.css',
	    'css/style.css',
	    'plugins/fancybox/jquery.fancybox.css',
	    'plugins/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.7',
	    'plugins/nivo-slider/nivo-slider.css',
	    'plugins/nivo-slider/themes/default/default.css'
	  );

	  createShortCutIcon('favicon.png');
  ?>
  <?php
	createJavascriptTag(
			"js/jquery.min.js",
			"js/bootstrap.min.js",
			"js/jquery-ui-1.9.2.custom.min.js",
			"plugins/fancybox/jquery.fancybox.pack.js",
			"plugins/fancybox/helpers/jquery.fancybox-media.js?v=1.0.6",
			"plugins/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.7",
			"plugins/nivo-slider/jquery.nivo.slider.pack.js",
			"plugins/mask/jquery.maskedinput.js",
			"js/script.js",
			"js/utfpr/utfpr.js",
			"plugins/bootstrap-rating-master/bootstrap-rating.js",
			"plugins/calendario/js/jquery.calendario.js",
			"plugins/calendario/js/modernizr.custom.63321.js"
		);
?>
</head>
	<body>
		<header>
			<?php require_once "views/default/admin/includes/_main-menu.phtml"; ?>
		</header>
		<div id="admin" class="container-fluid">
			<div class="row">
				<div id="content" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					
					<h1>Painel de Administração</h1>	

					<?php require_once "views/default/admin/includes/_flash.phtml"; ?>

					<?php require_once $this->getViewPath(); ?>					
				</div>
			</div>
			<footer id="footer">
				<?php require_once "views/default/admin/includes/_footer.phtml"; ?>
			</footer>	
		</div>

		<?php 

require_once "views/default/admin/includes/_modals.phtml" ?>

		<?php 

require_once "views/default/admin/includes/_foot.phtml" ?>
	</body>
</html>