<div class="row">
	<h2>Minhas Inscrições</h2>
	<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
		<ul class="list-group" style="text-align: left">
			<?php foreach ($this->enrollment as $enrollment) : ?>
				
				<?php if ($enrollment->getDatePayment()) : ?>
					<a href="<?=$this->getUri("conta/inscricoes/{$enrollment->getIdEnrollment()}")?>">
						<li class="list-group-item list-group-item-success">
							<span class="glyphicon glyphicon-ok-sign"></span>
							<?= $enrollment->event->getName() ?> - <b>Pagamento Confirmado</b>
						</li>
					</a>
				<?php elseif ($enrollment->getCost() == 0) : ?>
					<a href="<?=$this->getUri("conta/inscricoes/{$enrollment->getIdEnrollment()}")?>">
						<li class="list-group-item list-group-item-success">
							<span class="glyphicon glyphicon-ok-sign"></span>
							<?= $enrollment->event->getName() ?> - <b>Inscrição Gratuita</b>
						</li>
					</a>
				<?php else : ?>
					<a href="<?=$this->getUri("conta/inscricoes/{$enrollment->getIdEnrollment()}")?>">
						<li class="list-group-item list-group-item-warning">
							<span class="glyphicon glyphicon-exclamation-sign"></span>
							<?= $enrollment->event->getName() ?> - <b>Pendente</b>
						</li>
					</a>
				<?php endif ?>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
