<form action="<?= $this->actionForm?>" method="post">
	<div class="row">
		<div class="col-xs-12 col-sm-2 col-sm-offset-5">
			<h4>ID</h4>
			<input type="number" class="form-control" name="certificate[id_certificate]" value="<?= $this->certificates->getIdCertificate()?>" disabled/>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
			<h4>Selecione o evento</h4>
			<h6>OBS.: São listados apenas eventos que já terminaram.</h6>
				<select class="form-control" name="event">
				<?php foreach ($this->events as $event) : ?>
					<option value="<?= $event->getIdEvent()?>"><?=$event->getName()?></option>
				<?php endforeach ?>
			</select> 
		</div>
	</div>
	<div class="row" id="participant-row" style="display:none">
		<div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
			<h4>Selecione o participante</h4>
			<h6>OBS.: São listados apenas os participantes com presença confirmada.</h6>
				<select class="form-control" name="participant">
			</select> 
		</div>
	</div>


 		<br/>
	<button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok-circle"></span> <?= $this->titleBtnSubmit?></button>

<script type="text/javascript">
	enrollmentsUrl = '<?=createUriFor("/admin/certificados/inscricoes/")?>';
</script>

