<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 events-list">
	<div class="panel panel-default">
		<div class="panel-heading">
	    <h3 class="panel-title">Lista de certificados</h3>
	  </div>
	  <div class="panel-body">
	  	<span class="glyphicon glyphicon-question-sign" style="float:right;" title="Cada evento obrigatoriamente precisa ter um tipo, e é nesta área que os tipos são cadastrados." data-toggle="tooltip" data-placement="left"></span>
			<div class="row">
				<div class="col-xs-12 general-actions">
					<a href="<?= createUriFor('/admin/certificados/novo')?>">
						<button class="btn btn-success btn-sm" title="Cadastrar" style="float: left"><span class="glyphicon glyphicon-plus-sign"></span></button>
					</a>
					<div class="col-lg-4">
					  <div class="input-group">
					    <input type="text" class="form-control">
					    <div class="input-group-btn">
					      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" title="Procurar"><span class="glyphicon glyphicon-search"></span> <span class="caret"></span></button>
					      <ul class="dropdown-menu pull-right">
				          <li><a href="#">ID</a></li>
				          <li><a href="#">Nome</a></li>				          
				          <li><a href="#">Endereço Web</a></li>
				        </ul>
					    </div>
					  </div>
					</div>
				</div>
			</div>
		</div>
		<table class="table">
			<tr>
				<th>ID</th>
				<th>ID Inscrição</th>
				<th>Ações</th>
			</tr>
			<?php foreach ($this->certificates as $certificate) : ?>
				<tr>
					<td><?= $certificate->getIdCertificate() ?></td>
					<td><?= $certificate->getIdEnrollment() ?></td>
					<td>
						<a href="<?= createUriFor("/admin/certificados/{$certificate->getIdCertificate()}/ver") ?>">
							<button class='btn btn-primary btn-sm' title='Visualizar'>
								<span class='glyphicon glyphicon-eye-open'></span>
							</button>
						</a>
						<a href="<?= createUriFor("/admin/certificados/{$certificate->getIdCertificate()}/remover") ?>">
							<button class='btn btn-danger btn-sm' title='Excluir'>
								<span class='glyphicon glyphicon-trash'></span>
							</button>
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</table>
		<div class="panel-footer">
			<div class="row">
				<div class="col-xs-12">
					<ul class="pagination">
					  <?php echo $this->pagination->getPageAnchors("{$this->getUri('admin/certificados')}");?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>