<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 certificates-edit">
	
	<h2>Visualizar Certificado</h2>

	<?php require_once "_form.phtml"; ?>

	<a href="<?= createUriFor('/admin/certificados')?>">
		<button class="btn btn-warning" type="button"><span class="glyphicon glyphicon-arrow-left"></span> Retornar</button>
	</a>
	<a href="<?= createUriFor('/admin/certificados/'.$this->certificates->getIdCertificate().'/remover')?>">
		<button class="btn btn-danger" type="button"><span class="glyphicon glyphicon-trash"></span> Excluir</button>
	</a>

	</form>
</div>